project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Empirical and Corpus Studies in Music"
  description: "Homepage for Corpus Studies, Spring 2023 ."
  site-url: "https://shanahdt.github.io/mus-345-445/"
  repo-url: "https://github.com/shanahdt/mus-345-445"
  repo-actions: [edit, issue]
  # navbar:
  #   left:
  #     - href: index.qmd
  #       text: Home
  #     - href: course-syllabus.qmd
  #       text: Syllabus
  #     

  open-graph: true

  twitter-card:
    creator: "@danielshanahan"
    image: "images/twitter-card.png"
    

  sidebar:
    style: "docked"
    search: true
    title: false
    pinned: false
    collapse-level: 0
    contents:
      - section: "Resources"
        contents:
          - course-syllabus.qmd
          - course-schedule.qmd
        collapse-level: 1 
      - section: "Class Notes"
        contents:
          - class_notes/week_1.qmd
          - class_notes/week_2.qmd
          - class_notes/week_3.qmd
        collapse-level: 1
          

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2023, Daniel Shanahan"
    background: "#D9E3E4"


format:
  html:
    theme:
      light: [flatly, theme.scss]
      dark: [flatly, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true
