---
title: Corpus Studies (Music 348/448) Syllabus
output: html
---

## Instructor

Instructor: Dr. Daniel Shanahan

Contact: [daniel.shanahan\@northwestern.edu](mailto:daniel.shanahan@northwestern.edu)

## Overview

Corpus studies, or distant readings of multiple musical works, are often employed as a way of better understanding issues such as the relationships between pieces, authorship, trends over time, or differences and similarities between genres. In this class, we will explore the techniques, history, and philosophy of such approaches, and will construct and analyze our own corpora. For the most part, this class will deal with notated scores, and students will be encouraged to ask their own research questions of the music that they are most interested in.

## Course info

|                | Day                      | Time                     | Location   |
|----------------|:---------------|:------------------------|:---------------|
| Meeting Times: | Mon & Weds               | 12:30pm - 1:50 pm        | RCMA 1-164 |
| Office Hours   | TBD (and by appointment) | TBD (and by appointment) | RCMA 4-181 |

## Learning objectives

By the end of the quarter, you will...

-   have an understanding of how music has been examined through distant readings of scores and recordings
-   be able to explore how the concepts of concordances, schemata, key-finding, clustering, and introductory machine learning approaches can be applied to music analysis
-   have a working introductory knowledge of the [R programming language](https://www.r-project.org/about.html) and the [HumDrumR package](https://github.com/Computational-Cognitive-Musicology-Lab/humdrumR).

## Course Policies

### Academic Integrity

Students in this course are required to comply with the policies found in the booklet, "Academic Integrity at Northwestern University: A Basic Guide". All papers submitted for credit in this course must be submitted electronically unless otherwise instructed by the professor. Your written work may be tested for plagiarized content. For details regarding academic integrity at Northwestern or to download the guide, visit [this page](https://www.northwestern.edu/provost/policies-procedures/academic-integrity/index.html).

### Accesibility

Northwestern University is committed to providing the most accessible learning environment as possible for students with disabilities. Should you anticipate or experience disability-related barriers in the academic setting, please contact AccessibleNU to move forward with the university's established accommodation process (email: accessiblenu\@northwestern.edu; p: 847-467-5530). If you already have established accommodations with AccessibleNU, please let me know as soon as possible, preferably within the first two weeks of the term, so we can work together to implement your disability accommodations. Disability information, including academic accommodations, is confidential under the Family Educational Rights and Privacy Act.

### COVID-19 Classroom Expectations

Students, faculty and staff must comply with University expectations regarding appropriate classroom behavior, including those outlined below and in the [COVID-19 Expectations for Students](https://www.northwestern.edu/communitystandards/about-us/northwestern-university-student-expectations-covid-19.html). With respect to classroom procedures, this includes:

Policies regarding masking, social distancing and other public health measures evolve as the situation changes. Students are responsible for understanding and complying with current University, state and city requirements. In some classes, masking and/or social distancing may be required as a result of an Americans with Disabilities Act (ADA) accommodation for the instructor or a student in the class even when not generally required on campus. In such cases, the instructor will notify the class.

If a student fails to comply with the [COVID-19 Expectations for Students](https://www.northwestern.edu/communitystandards/about-us/northwestern-university-student-expectations-covid-19.html) or other University expectations related to COVID-19, the instructor may ask the student to leave the class. The instructor is asked to report the incident to the Office of Community Standards for additional follow-up.

#### If you're feeling sick...

Maintaining the health of the community remains our priority. If you are experiencing any symptoms of COVID **do not attend class**. Follow the steps outlined on the NU sites for testing, isolation and reporting a positive case. Next, contact me as soon as possible to arrange to complete coursework.

Should public health recommendations prevent in-person class from being held on a given day, I or the university will notify students.

### Diversity, Equity, and Inclusion

This course strives to be an inclusive learning community, respecting those of differing backgrounds and beliefs. As a community, we aim to be respectful to all students in this class, regardless of race, ethnicity, socio-economic status, religion, gender identity or sexual orientation.

## Textbooks

There is no textbook for this course, and most of the materials will be available on Canvas or the course website (or both). Many of the readings will be taken from the forthcoming [*Oxford Handbook of Music and Corpus Studies*](https://academic.oup.com/edited-volume/41992), edited by Daniel Shanahan, Ashley Burgoyne, and Ian Quinn.

Having said that, you should sign up for a free account for [Posit Cloud (formerly RStudio Cloud)](https://posit.cloud/), where many of the class notebooks will be held.I would also recommend downloading [R](https://www.r-project.org/about.html) and [RStudio](https://posit.co/download/rstudio-desktop/) onto your personal machine, if possible.

Although not required, I would highly recommend having a look at:

-   [R for Data Science](https://r4ds.had.co.nz/) by Garret Grolemund and Hadley Wickham
-   [The Humdrum User Guide](https://www.humdrum.org/guide/)
-   [The music21 documentation](http://web.mit.edu/music21/)
-   [*The Oxford Handbook of Music and Corpus Studies*](https://academic.oup.com/edited-volume/41992)

## Support for Wellness and Mental Health

Northwestern University is committed to supporting the wellness of our students. Student Affairs has multiple resources to support student wellness and mental health. If you are feeling distressed or overwhelmed, please reach out for help. Students can access confidential resources through the Counseling and Psychological Services (CAPS), Religious and Spiritual Life (RSL) and the Center for Awareness, Response and Education (CARE). Additional information on all of the resources mentioned above can be found here:

<https://www.northwestern.edu/counseling/>

<https://www.northwestern.edu/religious-life/>

<https://www.northwestern.edu/care/>

### Homework

There will be regular assignments in which you will be asked to respond to do one of the following:

-   Critically reflect upon a reading about the history, methods, and dilemmas commonly found in corpus studies.

-   Write code that addresses a musical question (e.g. what's the most common pitch transition in this group of pieces?)

-   Analyze a given collection of musical data.

Typically, we will have reading reflections due on Mondays, and code-related questions relevant to those readings due on Wednesdays.

### Midterm Project

The goal of this class is for you to both understand corpus studies as a method with a long history, and for you to be able to incorporate these methods in your own research. There will be a midterm project that is primarily used a stepping stone into your final project, and it will consist of presenting a literature review in which you situate your own research question within the existing literature and propose a study that examines this question. You may use existing data, but you might find it more relevant to you if you use your own dataset. Therefore, this would be a good time to have a bulk of your data encoded, so that you are aware of the time needed to construct your corpus.

### Final Project

The final project will be focused on a research question of your choosing, and will be broken up into several a peer-reviewed first draft, a presentation, and a final paper.

## Grading

The final course grade will be calculated as follows:

| Category                     | Percentage |
|:-----------------------------|:-----------|
| Reading Reflection Questions | 20%        |
| Code-focused assignments     | 30%        |
| Midterm Literature Review    | 15%        |
| Final Project (First Draft)  | 10%        |
| Presentation                 | 10%        |
| Final Project (Final draft)  | 15%        |

The final letter grade will be determined based on the following thresholds:

| Letter Grade | Final Course Grade |
|:-------------|:-------------------|
| A            | \>= 93             |
| A-           | 90 - 92.99         |
| B+           | 87 - 89.99         |
| B            | 83 - 86.99         |
| B-           | 80 - 82.99         |
| C+           | 77 - 79.99         |
| C            | 73 - 76.99         |
| C-           | 70 - 72.99         |
| D+           | 67 - 69.99         |
| D            | 63 - 66.99         |
| D-           | 60 - 62.99         |
| F            | \< 60              |

## Schedule

| Unit                                                     | Week | Date (Date)                   | Topic                                                         |
|---------------|:--------|:-----------------|:-----------------|
| Representing, Searching, and Counting with Symbolic Data | 1    | T (3/28; Northwestern Monday) | Introductions; a history of corpus-based approaches to music. |
|                                                          | 1    | W (3/29)                      | Representing musical data (kern, MIDI, XML, MEI)              |
|                                                          | 2    | M (4/3)                       | Pitches, melodic intervals and scale degrees                  |
|                                                          | 2    | W (4/5)                       | Representing Harmony                                          |
|                                                          | 3    | M (4/10)                      | Representing Rhythm and Meter                                 |
|                                                          | 3    | W (4/12)                      | Characteristic Features and TF-IDF                            |
|                                                          | 4    | M (4/17)                      | n-grams and Transition Probabilities                          |
|                                                          | 4    | W (4/19)                      | Finding patterns                                              |
| Conceptual Debates                                       | 5    | M (4/24)                      | Measurements of Similarity                                    |
|                                                          | 5    | W (4/26)                      | Entropy and Variability                                       |
|                                                          | 6    | M (5/1)                       | Key-Finding Algorithms                                        |
|                                                          | 6    | W (5/3)                       | Key-Finding Algorithms (*continued*)                          |
|                                                          | 7    | M (5/8)                       | Fast Fourier Transforms                                       |
|                                                          | 7    | W (5/10)                      | Clustering and Authorship                                     |
| Audio Data                                               | 8    | M (5/15)                      | Performance Data/the Mazurka Project                          |
|                                                          | 8    | W (5/17)                      | Tempo flexibility, and other performance data                 |
|                                                          | 9    | M (5/22)                      | The Spotify API                                               |
|                                                          | 9    | W (5/24)                      | The Spotify API (*continued*)                                 |
|                                                          | 10   | M (5/29)                      | No Classes (Memorial Day)                                     |
|                                                          | 10   | W (5/31)                      | Final Presentations                                           |