---
title: Course Schedule
---

## Schedule

| Unit                                                     | Week | Date (Date)                   | Topic                                                         | Important Dates                   |
|---------------|:--------------|:--------------|:--------------|:--------------|
| Representing, Searching, and Counting with Symbolic Data | 1    | T (3/28; Northwestern Monday) | Introductions; a history of corpus-based approaches to music. |                                   |
|                                                          | 1    | W (3/29)                      | Representing musical data (kern, MIDI, XML, MEI)              | Assignment #1 Due                 |
|                                                          | 2    | M (4/3)                       | Pitches, melodic intervals and scale degrees                  | Response #1 Due                   |
|                                                          | 2    | W (4/5)                       | Representing Harmony                                          | Assignment #2 Due                 |
|                                                          | 3    | M (4/10)                      | Representing Rhythm and Meter                                 | Response #2 Due                   |
|                                                          | 3    | W (4/12)                      | Characteristic Features and TF-IDF                            | Assignment #3 Due                 |
|                                                          | 4    | M (4/17)                      | n-grams and Transition Probabilities                          | Response #3 Due                   |
|                                                          | 4    | W (4/19)                      | Finding patterns                                              | Assignment #4 Due                 |
| Conceptual Debates                                       | 5    | M (4/24)                      | Measurements of Similarity                                    | Midterm Literature Review Due     |
|                                                          | 5    | W (4/26)                      | Entropy and Variability                                       | Assignment #5 Due                 |
|                                                          | 6    | M (5/1)                       | Key-Finding Algorithms                                        | Response #4 Due                   |
|                                                          | 6    | W (5/3)                       | Key-Finding Algorithms (*continued*)                          | Assignment #6 Due                 |
|                                                          | 7    | M (5/8)                       | Fast Fourier Transforms                                       | Response #5 Due                   |
|                                                          | 7    | W (5/10)                      | Clustering and Authorship                                     | Assignment #7 Due                 |
| Audio Data                                               | 8    | M (5/15)                      | Performance Data/the Mazurka Project                          | First Draft of Final Project Due  |
|                                                          | 8    | W (5/17)                      | Tempo flexibility, and other performance data                 | Assignment #8 Due                 |
|                                                          | 9    | M (5/22)                      | The Spotify API                                               | Response #6 Due; Peer Reviews Due |
|                                                          | 9    | W (5/24)                      | The Spotify API (*continued*)                                 | Assignment #9 Due                 |
|                                                          | 10   | M (5/29)                      | No Classes (Memorial Day)                                     | Final Presentations               |
|                                                          | 10   | W (5/31)                      | Final Presentations                                           | Final Papers due on Friday, 6/2   |