---
title: "Welcome!" 
date: "Thursday, January 6th, 2022"
format: 
  revealjs:
    incremental: true
    theme: league
    slide-number: true
---

## Hello!

Today we will be covering...

-   Introductions
-   The plan for the quarter
-   What is empirical musicology?
-   What is science?
    -   How does knowledge grow?

## Empiricism

> Empiricism isn't a method, it's just a smart thing to do.

--Gjerdingen (2011, SMT)

## What is empirical musicology?

> In short, there is no useful distinction to be drawn between empirical and non-empirical musicology, because there can be no such thing as a truly non-empirical musicology; what is at issue is the extent to which musicological discourse is grounded on empirical observation, and conversely the extent to which observation is regulated by discourse.

--Cook and Clarke (2004, p.3)

## Data-Rich vs. Data-Poor

-   Many aspects of musicology are "data-poor"
-   We have no real surviving original manuscripts in Josquin's own hand. Only a few contemporaneous ones.

## Data-Rich Responsibilities

> "...there would be grounds for legitimate criticism if musicologists working in data-rich fields did not take full advantage of the methds available under such conditions, instead restricting themselves to traditional"humanities" approaches developed for data-poor fields--and oe of the messages of this book is that musicology i or could be, in many instances, a significantly "data richer" field than we generally give it credit for."

--Cook and Clarke, (p.4)

## One more quote...

> Empirical musicology, to summarize, can be thought of as musicology that embodies a principled awareness of both the potential to engage with large bodies of relevant data, and the appropriate methods of achieving this \[...\]
>
> -- Cook and Clarke (2004, p.5)

## Types of Knowledge

-   Intuition
-   Deductive Knowledge
-   Empirical Knowledge

See [Types of Knowledge](../emp_methods_workshop/empirical.html)

## Intuition

-   A man about to cross the street jumps back when he hears the sound of a car horn. The reaction is so fast, he is not even aware of having thought about anything.

## Deductive knowledge

-   If all people are mortal, and Socrates is a person, then Socrates is mortal.
-   Seeing a guitarist move her finger one fret toward the tone hole, we conclude that the next pitch will be one semitone higher than the previous pitch.

## Empirical knowledge (knowledge gained through observation)

-   I've observed that some musicians can always identify the names of pitches ("perfect pitch") and others can't.

## Induction

-   "The problem of induction" (Hume)
-   "Reasoning by drawing a conclusion not guaranteed by the premises" (Dienes, p. 164)

## Induction

- Sam the swan is white; 
- Georgina the swan is white; 
- Fred the swan is white;
- ...
- Emma the swan is white.
- Conclusion: All swans are white.

## Proof

- Motivated by truth, with no hope of proof.
- We aim not to be right, but to be not not right.

## Popper

-   The goal of science is to test, criticize (and debunk) already existing theories.
-   It's not a bad thing if your theory is wrong.

## Demarcation

-   What makes something a science?
-   For Popper, something was a science if it contained falsifiable hypotheses.

## What makes something a hypothesis?

-   Conjectures
-   Hypotheses
-   Theories

## Why do you need a hypothesis?

-   Humans are very good at constructing narratives.
-   Hindsight bias is very real, and we should do everything we can to mitigate it.

## Operationalizing Terms

*Listening to Mozart makes people smarter.*

|               |                                                                      |
|:--------------|:---------------------------------------------------------------------|
| ***Concept*** | ***Possible operationalization***                                    |
| "smarter"     | will score higher on the Stanford-Binet IQ test                      |
| "Mozart"      | all sound recordings that claim the music is composed by W.A. Mozart |
| "listening"   | conscious while being exposed to 20 minutes of sound recordings      |
| "people"      | 2nd-year undergraduate music students from the Ohio State University |

## Types of Studies

See [this page on types of studies](../emp_methods_workshop/empirical2.html)
