---
title: "Sampling and Randomization" 
date: "Tuesday, January 17th, 2023"
format: 
  revealjs:
    incremental: true
    theme: league
    slide-number: true
---

## Midterms

- Due January 31 (two weeks from now!).
- 5-7 pages. 
- construct a literature review of the topic you're interested in writing about, culminating in a hypothesis section. 
- Feel free to meet with me if you have any questions.


## Midterms

- Be sure to include an overview of previous research related to the topic. This should include both empirical and non-empirical work. So if you're focusing on the memory for jazz licks, for example, research on improvisational styles should be included alongside work on memory for musical ideas. It need not be all-encompassing, but it should try to cover as much ground as possible.

## Midterms 
Address a gap in the current literature, or that between theory and research. End with a discussion of your study, and how it hopes to fill in these gaps.

# Sampling

## Populations

- A population is everything or everyone that you're interested in.
-   e.g. all the world's people
-   all the world's people including living and deceased
-   all Western-enculturated people
-   all people who enjoy listening to music
-   all clarinet players

## Populations (continued)

A "population" does not refer only to people: Other examples:

-   all of the music written by Vivaldi
-   all solo flute music (both with and without accompaniment)
-   all music in the minor mode
-   all of the jazz scores available in the New York Public Library
-   all performances of Rachmaninov's 2nd piano concerto

## Sample

- **Sample:** a subset of the population that you hope closely
resembles the population as a whole.

## Sample (Continued)

- A sample is said to be **representative** when the property of
interest is identical in both the sample and the population.

## Bias

- A sample is said to be **biased** when the property of interest
differs between the sample and the population.

## WEIRD

- Western
- Educated
- Industrialized
- Rich
- Democratic

[see Henrich's Work on this](https://en.wikipedia.org/wiki/The_WEIRDest_People_in_the_World)

## Defining Your Population

- You can't sample a population unless you have a clear idea of what
constitutes the population of interest.  

- Suppose, for
example, that you are a political pollster. Your aim is to predict
the likely election results for a national election in Denmark.
What, precisely, is the population you are interested in?

## Defining Your Population (continued)

-   All Danish citizens?
-   All people living in Denmark?
-   All people living in Denmark eligible to vote?
-   All people eligible to vote in Danish elections?
-   All people likely to vote in Danish elections?

## Sampling Method

- **Sampling method:** the way you recruit or assemble your sample.
When your population consists of people, sampling methods might
include soliciting information by telephone (telephone sampling),
street sampling, mail sampling, web sampling, classroom sampling,
concert sampling, etc.

## Sampling Bias

- **Sampling bias:** when the sampling method introduces differences
that cause the sample not to be representative. We try to avoid or
minimize sampling bias.

## Sampling Bias (continued)

- When conducting a telephone survey, a pollster may be tempted to ask
to speak to a respondent's spouse. However, spouses are likely to
share many things in common (such as political views) so the
sampling method will introduce a bias.

## Simple Random Sampling

- **Simple Random Sampling.** Suppose we want to know about
musical instrument sales in the City of Nashville. We could use
the phone book to identify all of the shops within the city boundaries that sell musical instruments. Perhaps we discover that there are 131 retailers. From this list, we might randomly select 25 retailers in order
to carry out our survey.

<!-- Note: 
Suppose we have a video recording of an audience listening to a
concert. Our hypothesis is that members of the audience "figet"
more when listening to Schoenberg compared with Ravel. The video
camera allows us to see 150 audience members and the recording
lasts 40 minutes. Counting the figets for each audience member
over the entire recording would require too much work. To
simplify the problem, we might randomly select 25 of the 150
audience members. In addition, instead of coding data for the
entire video, we might count the number of figets during twenty
randomly selected 10-second segments: ten 10-second segments
from the Schoenberg work and ten 10-second segments from the
Ravel. Here we are randomly sampling from the total visible
audience, and also randomly sampling from the total length of
the video recording. -->

## Systematic Sampling 

Suppose that we have a questionnaire we want to distribute to
people who attended a concert. There might be 500 audience
members, but we have only 50 surveys to distribute. One approach
would be to distribute the questionnaires to the first 50 people
leaving the concert hall. 

## Matched Random Sampling

- A way of linking members from two
or more samples. For example, a study might involve matching
each professional musician with an amateur musician who plays
the same instrument.

## Convenience Sampling

- **Convenience Sampling.** A convenience sample simply takes
advantage of whatever might be available. For example, a sample
of organ music by Gabriel Fauré might simply consist of all of
the scores available in a music library. Similarly, we might
stand on a street corner and ask whoever passes by to answer
questions on a survey.

## Stratified Sampling

- When we have reason to suspect that difference in sub-populations might influence the results, it is common to sample in such a way to ensure that each of the main sub-populations are represented.

## Stratified Sampling (Continued)

- Post and Huron (2009) were interested in common-practice era tonal classical music. So we decided to use a stratified sample consisting of music from three periods: Baroque, Classical and Romantic. Our overall sample consisted of equivalent numbers of works from each of these historical eras.

## Quota Sampling

- A type of stratified sampling in which sub-samples are weighted according to their prevalence in the population. 

## Quota Sampling

- Suppose that we find that 52% of instrumentalists are most accomplished on guitar, 33% are most accomplished on keyboards, 12% on flute, 9% on trumpet, 8% on violin, etc. In quota sampling, we would aim to sample the same proportions for each instrument.

## Exercise

[Group Exercise](../emp_methods_workshop/samples.qmd)

## Exercise (Answers)

[Group Exercise (Answers)](../emp_methods_workshop/samples_answers.qmd)

