

------------------------------------------------------------------------

### Anecdotal Evidence

------------------------------------------------------------------------

In 1966, Peter Wason published an article showing a peculiar aspect
of human reasoning. He devised the following task. Various cards are
presented: each card has a number written on one side and a letter
written on the other. There is a rule: *any card having a vowel on
one side has an even number on the other.* Now suppose you are
looking at four cards with the following visible characters:

A

B

4

7

Which of the four cards should you turn over in order to check whether
the rule has been followed? (It's important to try this task before
continuing to read.)

The correct answer is: turn over A and 7. You need to turn over A to
make sure there is an even number on the back. You need to turn over 7
in order to ensure that it doesn't have a vowel on the back.

Now consider the following variant on the task. In this case, the cards
now contain different information. On one side of the card is the age of
a person at a bar. The other side of the card identifies what it is that
the person is drinking. Once again, there is a rule: *anyone drinking
alcohol must be 21 years of age or older.* Your task is to identify
which cards to turn over in order to check whether the rule is followed:

beer

cola

16

25

Most people find this problem trivial. You need to check the age of the
beer-drinker, and you need to check what the 16-year-old is drinking.

What's important is that the two problems are logically identical, but
people have a much easier time understanding (and correctly solving) the
second problem compared with the first. Why?

In 1977, Roger Schank and Robert Abelson published an influential book
entitled *Scripts, Plans, Goals and Understanding*. In that book they
reviewed research in social psychology showing that human knowledge and
understanding are deeply rooted in stories and storytelling. Research
persistently shows that people are not interested in numbers. We are
interested primarily in other people and in hearing about the
experiences of other people. The second version of the Wason card task
is easier to solve because the problem is less abstract and more more
story-based.

Charities have learned the importance of story-telling. For example,
many charities (*Oxfam, Save The Children, CARE, UNICEF, Mercy Corps,*
etc.) are involved in trying to alleviate hunger and starvation. In
their advertising, these charities have learned to avoid abstract
appeals. A charity appeal that notes that one million people are
currently experiencing starvation in Somalia has surprisingly little
effect. Video footage of a single starving child (who is given a name)
is far more effective than video footage showing a sea of starving
people in refugee camps.

It is easier for people to comprehend concrete examples rather than
abstract ideas. This lesson also applies to music research. A musical
concept is best conveyed by offering a musical example rather than
presenting an abstract generalization. Although a music theorist may
appreciate a formal statement, most theorists prefer some good musical
examples that illustrate the idea. The example will be especially
compelling if the specific musical work is well-known and so easily
recalled.

#### Stories

The research suggests that narratives involving individual people,
examples, or events are easier to understand than abstract principles
or large numbers. At the same time, human-oriented narratives are more
memorable. We remember anecdotes about people better than statistical
facts (Schank & Abelson, 1977). When people gather together, they tend
to relay stories; these stories include not only first-hand
experiences, but also the recounting of stories we have heard from
other people.

People find *People* magazine much more compelling to read than
reports from the U.S. Bureau of Labor Statistics. There are compelling
human concerns behind labor statistics, but because these numbers are
faceless, people don't find them interesting.

Schank and Abelson have noted that people's memories of essential
facts are indexed in the brain around stories. If we are presented
with a fact that is accompanied by a story, the research shows that we
are more likely to remember it. However, when we are presented with
facts without a story, that fact enters short-term memory, but
typically never makes it into long-term memory.

On the pacific island of Tongatapu, I spent considerable time
listening to local radio broadcasts. From my field notes, I know that
my tallies suggest that the most popular music on the island was
reggae. However, I don't remember any of the specific tallies, or any
of the specific recordings I heard on the radio. What I do recall is
asking a taxi driver what his favorite music was: He said "reggae." I
recall the vehicle, the driver, and even the specific road on the
island where he responded to my question. But I don't even remember
any of the times I spend monitoring the radio or making notes on
broadcast statistics.

#### The Utility of Stories

There are two places where anecdotes have a role in research. First,
anecdotes are a legitimate part of exploratory research. Anecdotes can
provide useful starting points for formulating theories which can then
be tested using formal empirical methods. Second, anecdotes provide
memorable illustrations or examples --- but only when the empirical
research supports the *general* lesson illustrated by the anecdote.

Because narratives can be quite memorable, we should always try to
make use of narratives in our teaching. Let the research speak, and
then cement the lesson by adding an appropriate anecdote. Journalists
love to do this. Even when a journalist is reporting research --- say,
about sleeping --- they will typically try to personalize the article
by starting with an individual case or a specific anecdote: "For
years, Jill Johnson had suffered from chronic sleep problems ...."
The above anecdote regarding reggae on Tongatapu is a concrete
example.

#### Problems

There are at least four problems with anecdotes. First, anecdotes can
be mentally *too* compelling. A good anecdote will trump reasoned
argument. Anecdotes are easily recalled when they go against
expectations. For example, some people have died in automobile
accidents because they got tangled in a seat belt. However, seatbelts
save many more lives than they end. One or two ancedotes can have an
enormous impact on people's willingness to wear seatbelts.
Unfortunately, ancedotes commonly trump research statistics.

The second problem with ancedotes is that they are not systematically
or randomly sampled and so are rarely representative. The most
successful book ever published on music and the brain is Oliver
Sacks's *Musicophilia.* Each chapter describes a different case study
--- a single person --- and how brain damage influenced their
relationship with music. For example, Sacks describes an unforgetable
case of a man who became a passionate performer after being struck by
lightning. The story is fascinating, but it is hardly representative.
Being struck by lightning rarely changes one's appreciation for music.
Sacks is the first to admit that he is not a researcher or a scholar.
He modestly notes that "I'm really just a neurological story-teller."

A third problem is that anecdotes tend to attract similar anecdotes.
In ordinary conversation, for example, if a person relays a positive
anecdote about Sam, the story is likely to evoke further positive
anecdotes about Sam. Conversely, if someone says something negative
about Sam, the comment is likely to evoke further negative anecdotes
about Sam. This tendency for stories to elicit similar stories is
known as the *bandwagon effect.* The bandwagon effect exaggerates a
given view and makes it seem more commonplace than is the case ---
that is, ancedotes tend to amplify sampling bias.

A fourth problem is that anecdotes are often *volunteered* rather than
*elicited.* Often, people have an underlying motive or goal in telling
the story. The story-teller is likely to have an "agenda" or a
particular point-of-view that is being actively promoted by telling
one story rather than another.

In light of the sampling problems related to anecdotes, haphazard
collections of anecdotes should not be used as data for testing a
theory or hypothesis. Our slogan reminds us to be wary of anecdotal
information:

**Slogan:** *The plural of anecdote is not data.*

By way of summary, anecdotes play an important role in exploratory
research (the context of discovery): many good theoretical insights
arise from the stories people tell about their experiences. Anecdotes
also serve as invaluable memory aids for illustrating particular ideas
--- ideas that are supported by solid empirical evidence. However,
anecdotes should play no role in the context of justification. Due to
the haphazard manner in which most anecdotes are collected, they are
rarely representative.

#### References

Oliver Sacks (2007). *Musicophilia: Tales of Music and the Brain.* New
York: Alfred A. Knopf.

Roger Schank and Robert Abelson (1977). *Scripts, Plans, Goals and
Understanding.* New York: Wiley.

Roger Schank and Robert Abelson (1995). Knowledge and memory: The real
story. In Robert S. Wyer Jr. (ed.), *Knowledge and Memory: The Real
Story.* Hillsdale, NJ: Erlbaum, pp. 1-85.

Peter Wason (1966). Reasoning. In Foss, B. M. *New Horizons in
Psychology.* Harmondsworth: Penguin.




