

------------------------------------------------------------------------

## Measures of Central Tendency: Mean, Median, Mode

------------------------------------------------------------------------

#### Mean (or average)

**Q.** What is an average?

**A.** The sum of all values divided by the number of values.

**Q.** Why calculate an average?

**A.** To reduce the effect of noise when estimating a population
norm.

Calculating an average can sometimes allow you to see a pattern
that is otherwise invisible.

**Q.** When can I calculate an average?

**A.** Two conditions are necessary: (1) All of the values have
been drawn from the same population. (2) The values are normally
distributed.

**Q.** How do I know whether the values are normally distributed?

**A.** Graph the values and see whether the values cluster in a
single region, or in two or more regions.

(There are also formal statistical methods that can be used to
estimate whether a set of values all belong to a single
population.)

#### Median

**Q.** What is a median?

**A.** The middle value of an ordered list of numbers.

**Q.** When is it appropriate to calculate a median?

**A.** When all of the values are drawn from the same population.
The values may or may not be normally distributed. When the
distribution is not normal, the median is preferred over the mean
as a representative measure of central tendency

#### Mode

**Q.** What is a mode?

**A.** The mode is the most commonly occurring value in some set.

**Q.** When is it appropriate to calculate a mode?

**A.** When all of the values are drawn from the same population.
The values may or may not be normally distributed. The mode is the
preferred measure of tendency when the values are are nominal. For
example, in Western art music, the most commonly occurring key is
G major. That is, G major is "mode" (in the statistical sense) for
the set of all music keys. In an orchestral ensemble, the mode
instrument is the violin.




