


------------------------------------------------------------------------

## Judging Performance Quality: Sight versus Sound

------------------------------------------------------------------------

In 2013, Chia-Jung Tsay published an article entitled "Sight over
sound in the judgment of music performance" in the *Proceedings of the
National Academy of Sciences* (Vol. 110, No. 36, pp. 14580-14585). The
full article can be accessed at:
www.pnas.org/content/110/36/14580.full

*In general, Tsay carried out a series of seven experiments. For all
seven experiments, Tsay made use of brief (six-second) excerpts from
performances from 10 major music competitions. The excerpts were
randomly selected from full performances by the three finalists in
each competition. Thus the stimuli involved 30 different performers.
In all seven experiments, participants were asked to judge which of
three finalists was the actual winner of the competition. Some of
the excerpts consisted of sound only; other excerpts consisted of
video only (no sound); yet other excerpts included both sound and
video. In experiments 1, 2, and 3, Tsay made use of non-expert
listeners. In experiments 4, 5, 6 and 7, Tsay made use of
professional musicians who were experienced in judging music
competitions. Below are quoted extracts from the published article
that summarize the results:*

*ABSTRACT:* "Social judgments are made on the basis of both visual and
auditory information, with consequential implications for our
decisions. To examine the impact of visual information on expert
judgment and its predictive validity for performance outcomes, this
set of seven experiments in the domain of music offers a conservative
test of the relative influence of vision versus audition. People
consistently report that sound is the most important source of
information in evaluating performance in music. However, the findings
demonstrate that people actually depend primarily on visual
information when making judgments about music performance. People
reliably select the actual winners of live music competitions based on
silent video recordings, but neither musical novices nor professional
musicians were able to identify the winners based on sound recordings
or recordings with both video and sound. The results highlight our
natural, automatic, and nonconscious dependence on visual cues. The
dominance of visual information emerges to the degree that it is
overweighted relative to auditory information, even when sound is
consciously valued as the core domain content."

"Experiment 1: Core Beliefs About Music. Suppose that you have the
chance to win cash bonuses if you can guess who won a live music
competition. You may choose the type of recording you think would give
you the best chance at winning the prize. You can select sound
recordings, video recordings, or recordings with both video and sound.
Which recordings do you choose? In experiment 1, participants were
asked to make exactly that decision and bet their study earnings on
their choices."

"As expected, 58.5% chose the sound recordings, significantly more so
than the 14.2% who chose video recordings, *X*^2^(df=1, n=77)=28.89,
*p*<0.001. Despite a 'tax' levied on selecting the recordings with
both video and sound, 27.4% still chose those recordings, a
significantly larger proportion than those who chose the video
recordings, *X*^2^(df=1, n=44)=4.46, *p*=0.035. People have the
intuition that sound is a more revealing channel of information in the
domain of music and that recordings with both visual and auditory
output offer additional and more relevant information that better
approximates the conditions under which the original expert decisions
were made."

*Notice that when selecting which of three finalists is the winner,
a chance level of performance would be 33% correct.*

"In experiment 2, novice participants were presented with both
video-only and sound-only versions of 6-s clips of the top
performances from international competitions. Although 83.3% of
participants reported that the sound mattered most for their
evaluation of music performance, these same participants were
significantly more likely to identify the winners when they were
presented with only the visual components of the performances,
*t*(105)=12.07, *p*<0.001 ... (Fig. 1). The ... effect held across
all 10 competitions, *t*(9)=4.37, *p*=0.002. Indeed, with silent
video-only recordings, participants were significantly above chance
(52.5%), *t*(105)= 10.90, *p*<0.001. With sound-only recordings, they
were significantly below chance (25.5%) at identifying the winners,
*t*(105)=-5.23, *p*<0.001."

[Experiments 4 and 5 made use of expert musicians who] "had
participated in and judged competitions and are familiar with how
professional judgment is determined."

"In experiment 4, 96.3% of domain-expert participants reported that
the sound mattered more for their evaluations, *X*^2^(df=1,
n=27)=23.15, *p*<0.001. Despite musicians' training to use and value
sound in their evaluations, only 20.5% of experts identified the
winners when they heard sound-only versions of the recordings,
*t*(34)=-6.11, *p*<0.001. However, 46.6% did so upon viewing silent
video clips, *t*(34)=4.05, *p*< 0.001. Those with video-only stimuli
performed significantly better, compared with those who heard
sound-only stimuli, *t*(34)=5.89, *p*<0.001 ..."

*In the subsequent experiments, Tsay attempted to identify which
visual features are most influential in rendering judgments. He
compared simple images of the performer (that would indicate race,
sex, age, physical attractiveness) with modified video that obscured
these features, but left the motion and physical gestures intact.*

"The importance of dynamic visual information to professional judgment
was further established through two supplementary experiments.
Although demographic cues such as race and sex have been associated
with various capabilities (Bertrand & Mullainathan, 2004; Pager, et
al. 2009), such as the quality of musicianship (Goldin & Rouse,
2000)---and although the many advantages of physical attractiveness
have been documented (Dion, Berscheid & Walster, 1972), from hiring
(Beehr & Gilmore, 1982) to income (Biddle & Hamermest, 1998)---these
static visual cues did not significantly impact professional judgment
in these competitions."

"Passion had considerable impact on the professional judgment of
quality when it was visible; through silent videos, those selecting
'the most passionate contestant' identified the actual winners at
rates significantly higher than chance (59.6%)."

**Question for discussion:** What do you make of Tsay's conclusion?
I.e., "People consistently report that sound is the most important
source of information in evaluating performance in music. However, the
findings demonstrate that people actually depend primarily on visual
information when making judgments about music performance."




