
**Materials Copyright © 2018, 2019 by David Huron**


# Methods in Empirical Music Research A Workshop for Music Scholars

N.B. This document is effectively the Table of Contents for all of
the text documentation (web pages) for the workshop. The
instructor uses this page to access presentation materials. At the
end of each day, participants receive an edited copy of this
contents document up to the end of the particular workshop day. At
the end of the workshop, participants receive an edited copy of
the entire document and copies of all the linked web pages.
Depending on timing it will be necessary to omit some of planned
workshop material. Content materials are marked as follows:

**[1]** - means essential material, don't skip
**[2]** - means important material, aim to include
**[3]** - means unessential material, can omit depending on
time
**[H]** - to be presented by Huron
**[S]** - to be presented by Shanahan
**[H/S]** - to be presented by Huron & Shanahan
Lines beginning with a plus sign [**+**] are comments for the
instructors. These lines will be deleted in the document sent to
participants.



------------------------------------------------------------------------

**DAY 1**

------------------------------------------------------------------------

-   [Title page](title_workshop.html)

1.  **Welcome & Introduction**
    -   +[Introduction](intro.html) **[1][H/S]**
2.  **Generals Aims & Preview**
    -   [Day 1 Program](program1.html) + Participants receive a
        printed copy of the program at the beginning of each day.
        **[1][S]**
    -   [Learning objectives](goals.html) **[1][S]**
3.  **Empirical Research**
    -   [Preamble: An Arts and Humanities Approach to Empirical
        Method](preamble.html) **[3][H]**
        +(Philosophical [continental phenomenological or formal logic
        approach to content;
        +Science [procedural orientation; norms of scientific
        method]
        +Humanities approach [We approach it from a rhetorical and
        ethical perspective]
        +Please read the "Preamble" as part of your homework today.)
    -   [Types of knowledge](empirical.html): Inductive, Deductive,
        Intuitive [(powerpoint presentation
        #1)](01_knowledge_types.pdf) **[1][H]**
    -   [Seven big ideas](big_ideas.html)
        1.  [No Proof:](big_ideas.html#No%20Proof) *Motivated by
            truth, with no hope of proof.* **[1][S]**
        2.  [Inviting Failure:](big_ideas.html#Inviting%20Failure)
            *The best research invites failure.* **[1][H]**
        3.  [Testing
            Predictions:](big_ideas.html#Testing%20Predictions) *We
            invite failure by testing predictions.* **[1][S]**
        4.  [Recognizing
            Failure:](big_ideas.html#Recognizing%20Failure) *We
            recognize failure by drawing a line in the sand.*
            **[1][H]**
        5.  [Refutation is Easier than
            Confirmation:](big_ideas.html#Refutation) *Aim not to be
            right, but to be not not right.* **[1][S]**
        6.  [Operationalizing:](big_ideas.html#Operationalizing) *Test
            hypotheses by operationalizing terms.* **[1][H]**
            [Essentializing:](big_ideas.html#Essentializing)
            *Operationalize, but don't essentialize.* **[1][H]**
        7.  [Control:](big_ideas.html#Control) *Compare, compare,
            compare.* **[1][S]**
            *Counterfactuals:* [(powerpoint presentation
            #2)](02_counterfact.pdf) **[1][H]**
            [Randomized Control Studies - The Case of
            Microfinance](compare.html) +For participant reading
            only.
    -   [The rhetoric of science](prophecy.html)
        ([video](http://vimeo.com/63377111) - 8 minutes)
        **[1][H]**
        -   *Prophetic Rhetoric:* *The rhetoric of science is the
            rhetoric of prophecy.*
            "Science is a narrative activity, conducted by a
            community of scholars who hold each other to a
            methodological commitment to making and testing
            predictions."
    -   Review the first 9 slogans: [Quiz #1](quiz1.html)
        **[1][S]**
    -   **Group Task #1:** [What's worth knowing? An audience with
        God](god_questions.html) **[1][H]**
    -   [Questions, conjectures, hypotheses and
        theories](hypotheses.html) **[1][S]**
    -   **Group Task #2:** [Question, theory or
        hypothesis?](theory_hypothesis.html) **[1][H]**
        [(Answers)](theory_hypothesis_answers.html) **[1][H]**
    -   [Grandmother research](grandmother.html) **[1][S]**
    -   [The quantitative/measurement obsession](quantitative.html)
        **[1][H]**
    -   **Group Task #3a:** [Obvious theories - Part
        1](hindsight_task1.html) **[1][S]**
    -   **Group Task #3b:** [Obvious theories - Part
        2](hindsight_task2.html) **[1][H]**
    -   [(Group Task #3 Debriefing) Obvious theories: Hindsight
        bias](hindsight_task3.html)
        10. *Hindsight is 20/20.* **[1][H]**
    -   [Grandparent research revisited](grandmother2.html)
        **[1][S]**
    -   [Two forms of reductionism](reductionism.html)
        11. *In research, reductionism is a method, not a belief.*
        12. *Don't try to explain the whole world at once.*
            **[1][H]**
    -   [Epistephobia](epistephobia.html) **[2][S]**
    -   [Types of failure](truth.html) [(powerpoint presentation
        #3)](03_failure_types.pdf) **[1][H]**
    -   [Review (first 12) slogans](slogans12.html) **[1][S]**

```{=html}
<!-- --
```
4.  **Types of Empirical Studies**
    -   [Types of empirical studies](empirical2.html) [(powerpoint
        presentation #5)](05_empirical_studies.pdf) **[1][H]**
    -   **Group Task #4:** [Types of studies](types.html)
        [(Answers/Discussion)](types_answers.html) **[1][S]**
    -   [Generalizing versus universalizing](generalize.html)
        ([video](http://vimeo.com/66280977) - 10 minutes)
        **[1/2][H]**
        13. *Generalize, but don't universalize.*
    -   [Exploratory studies](exploratory.html) **[1][S]**
    -   [Measurement studies](measurement.html) **[1][H]**
    -   [Hypothesislessness](hypothesisless.html)
        14. *Avoid chronic hypothesislessness.* **[1][S]**
    -   **Group Task #5:** [Operationalize the following
        hypotheses](operationalize_this.html) **[1][H]**
    -   [Syncopation: From question to hypothesis](syncopation.html)
        (powerpoint presentation #8) **[3???][H]**
    -   [Opinions as
        operationalizations](operationalize_opinions.html)
        **[2][S]**
    -   [Double use data](double_use.html)
        15. *Beware of the post hoc theory.* **[1][H]**
    -   [Exploratory & Confirmatory: Contexts of discovery and
        legitimation (lecture)](origins.html) **[2][S]**
    -   [Explore-then-test Approach](explore_then_test.html)
        **[1][H]**
    -   [Explore-then-test example - Part 1](explore_then_test1.html)
        (Have a participant read the text aloud. What kind of study is
        this? What should happen next?) **[2][S]**
    -   [Explore-then-test example - Part 2](explore_then_test2.html)
        (Have another participant read the text aloud. Why make use of
        a robot rather than a human?) **[2][S]**
    -   From question ... to protocol.
        16. *From question to theory to conjecture to hypothesis to
            protocol* **[2][H]**
    -   [Quiz #2](quiz2.html) **[2][S]**
        [(Answers)](quiz2_answers.html) **[2][S]**
    -   [Review (first 16) slogans](slogans16.html) **[1][S/H]**
    -   Tomorrow: would encourage everyone to mix-up the
        seating/groups.
    -   [Feedback Day 1](feedback1.html) **[1][H]**
5.  **Homework** **[1][H]**
    -   *Homework 1:* [Reading: Preamble: An Arts and Humanities
        Approach to Empirical Method](preamble.html) *Homework 2:*
        [Reading Guide #1: Lancashire & Hirst (2009)](reading01.html)
    -   [Reading #1: Lancashire &
        Hirst (2009)](Agatha_Christie2009.pdf)
    -   *Homework 3:*
        **Individual Task #6:** [From question to
        theory](question2theory.html)

------------------------------------------------------------------------

**DAY 2**

------------------------------------------------------------------------

6.  **Review and Elaborations**
    -   **Welcome** **[1][H]**
    -   [Day 2 Program](program2.html) **[1][S]**
    -   [Review slogans (first 16)](slogans16.html) **[1][H/S]**
    -   **Group Task #7:** [From theory to
        conjecture](theory2conjecture.html) **[1][H]**
    -   [Multiple operationalizations](09_gauvin.pdf) **[3][S]**
    -   [Formal observation: The taxi protocol](protocol.html)
        **[3][H]**
    -   [The Experiment](experiment.html) **[1][S]**
    -   [The Correlational Study](correlational_study2.html)
        **[1][H]**
    -   [Correlation and causation](causality.html) **[1][H]**
    -   The third variable problem
        17. *No causation without manipulation.* **[1][H]**
7.  **Sampling**
    -   [Sampling](sampling.html) **[1][S]**
    -   **Group Task #8:** [Sampling Approaches
        **[1][H]**](samples.html)
        [(Answers)](samples_answers.html) **[1][H]**
    -   WEIRD sampling (Western, Educated, Industrialized, Rich,
        Democratic) **[3][S]**
    -   [Data Independence](data_independence.html) **[1][H]**
        18. *Avoid sticky data.* **[1][H]**
    -   [Biased Sampling: Listening to Edith
        Boyd](sampling_haphazard.html) **[2][H]**
    -   **Group Task #9:** [Sampling Issues](sampling_problems.html)
        [(Discussion)](sampling_problems_answers.html)
        **[1][H/S]**
    -   **Group Task #10:** [What is Random?](random.html)
        **[1][S]**
    -   **Homework review:** [Review questions and answers for
        Lancashire & Hirst (2009)
        **[3][H]**](Readings/reading01.html)
    -   [Sampling - A Practical Problem](sampling2.html) [omit?]
        **[3][H/S?]**
    -   [Sample Size: Law of Big Numbers](big_numbers.html)
        **[1][S]**
    -   [Sample Size: Law of Small Numbers](small_numbers.html)
        **[1][S]**
        19. *The law of large numbers does not apply to small
            numbers.* **[1][S]**
    -   [Effect Size](effect_size.html) **[1][H]**
    -   [Regression-to-the-Mean](regression_to_mean.html)
        **[1][S]**
    -   [Regression-to-the-Mean in Music](regression_in_music.html)
        **[3][H??]**
    -   [Review (first 19) slogans](slogans19.html) **[1][S/H]**
    -   **Group Task #11:** [Are dynamics
        asymmetrical?](dynamics.html) [Data sheet](dynamics2.html)
        **[1][H/S]**
8.  **Behavioral Data**
    -   Dependent and independent measures **[1][S]**
    -   [Types of behaviors (summary)](behaviors_brief.html) The full
        text (or video) are left as homework. [Types of behaviors
        (full)](behaviors.html) ([video](http://vimeo.com/65008608) -
        32 minutes) **[3][H]**
    -   Implicit vs. explicit responses **[2][S]**
    -   [Reactivity](reactivity.html) **[2][H]**
    -   [Demand characteristics](demand_characteristics.html)
        **[1][S]**
        [Clever Hans](cleverHans.html) **[1][H]**
        20. *Always debrief.* **[1][S]**
    -   [Measurement scales](scales.html) **[1][H]**
    -   **Group Task #12:** [What kind of measurement
        scale?](measurement_scales.html)
        [(Answers)](measurement_answers.html) **[1][S]**
    -   [Designing questionnaires](questionnaires.html) (powerpoint
        presentation #17) **[2][H]**
    -   **Group Task #13:** [Questionnaire Design
        **[2][H]**](questionnaire_task.html)
    -   [Review (first 20) slogans](slogans20.html) **[1][H/S]**
    -   [Feedback Day 2](feedback2.html) **[1][H]**
9.  **Homework** **[1][H]**
    -   [Reading Guide #2: Perttu (2007)](Readings/reading02.html)
    -   [Reading #2: Perttu (2007)](Readings/perttu.pdf)

------------------------------------------------------------------------

**DAY 3**

------------------------------------------------------------------------

10. **Introduction to Statistics**
    -   [Day 3 Program](program3.html) **[1][S]**
    -   [Outline (lecture)](stats_day_outline.html) **[1][H]**
    -   [Why measure? How to measure anything](measure_anything.html)
        **[1][H]**
        *Measurement* (powerpoint presentation #18) **[1][H]**
    -   Fermi Questions: Are there a half a billion windows in New
        York City? Are there 500 piano tuners in Chicago? [You may be
        better than you think you are at estimating some values.]
        **[3][H]**
    -   [Descriptive Statistics](stats_descr.html) **[1][S]**
    -   [Measures of Central Tendency](average.html) [powerpoint
        presentation](19_desc_stats.pdf) **[1][S]**
    -   **Group Task #15:** [Descriptive
        Statistics](desc_stats_task.html) **[1][S]**
    -   [Inferential Statistics](stats_infer.html) **[1][H]**
    -   [Inferential Statistics](20_inferential_stats.pdf) (including
        [Probability](probability.html), [The null
        hypothesis](null_hypothesis.html), Confidence and significance
        levels, Statistical tests) **[1][H]**
    -   [Confidence level and Confidence
        Interval](confidence_level.html) **[1][H]**
    -   [Calculating confidence interval from confidence
        level](http://www.surveysystem.com/sscalc.htm) (web tool)
        **[1][S]**
    -   [Statistical Significance](significance.html) **[1][S]**
    -   [Chi-square test](chi_test.html) (powerpoint presentation #22)
        **[2][H]**
    -   [Table of critical values for chi-square
        (short)](chi_table_short.html) [(long table - 5
        pages)](chi_table.html) **[2][H]**
    -   **Group Task #16:** [Chi-square
        tests](chi_square_problems.html);
        [(Answers)](chi_square_answers.html) **[2][H/S]**
    -   **Group Task #17:** [Funeral marches in F minor:
        Hypothesis](funeral_marches.html)
        [(Answer)](funeral_answers.html) **[2][H/S]**
    -   Correlation demonstration [Pearson's r
        Table](PearsonRtable.pdf); **[2][H]**
    -   Spurioius correlations - see
        <http://www.tylervigen.com/spurious-correlations
        **[1][S]**
    -   [Interpreting *p*; "Highly" and "marginally"
        significant](highly_significant.html) **[1][H]**
    -   [Multiple Tests and Related Topics](multiple_tests.html):
        Bonferroni Correction; File Drawer Effect **[1][S]**
        22. *Correct for multiple tests.* **[1][H]**
    -   Positive results bias. The case of Ego Depletion (video - 9
        minutes) **[2][H]**
    -   Concept of "research registry" **[2][S]**
    -   [Reporting Statistical Results](23_reporting.pdf)
        **[1][H]**
    -   [Statistical tests - General remarks](stats_conclude.html)
        **[1][H]**
        21. *Make friends with a statistician.* **[1][S]**
11. **Applied Statistics**
    -   Heroes and villains in opera (simplified analysis using
        chi-square test) **[1][S]**
    -   Population density and tempo (demonstrating Pearson's r)
        **[1][S]**
    -   German vs. Chinese folksongs (regression analysis)
        **[3][S]**
12. **Some Advanced Analytic Techniques**
    -   [Advanced Analytic Techniques](25_advanced_stats.pdf)
        **[1][H]**
    -   [Cluster analysis: Orchestration](orchestration.html)
        **[2][S]**
        [Cluster analysis: From Classical to
        Romantic](romanticism.html) **[2][H]**
    -   [Multi-dimensional scaling (MDS)](mds.html) **[2][S]**
    -   [Modeling - B-flat trumpet](modeling.html) **[1][H]**
        23. *If you torture the data long enough, it will confess to
            anything.* **[1][S]**
    -   Foote Novelty (powerpoint presentation #26) **[3][H]**
    -   **Homework review:** [Review questions and answers for Perttu
        (2007) **[2][S]**](perttu.html)
    -   [Review (first 23) slogans](slogans23.html) **[1][H/S]**
    -   [Feedback Day 3](feedback3.html) **[1][H]**
13. **Homework** **[1][H]**
    -   [Reading Guide #3: Shanahan & Huron (2014)](reading03.html)
    -   [Reading #3: Shanahan & Huron (2014)](heroes_villains.pdf)

------------------------------------------------------------------------

**DAY 4**

------------------------------------------------------------------------

14. **Review**
    -   [Day 4 Program](program4.html) **[1][S]**
    -   Review yesterday's slogans:
        21. *Correct for multiple tests.*
        22. *Make friends with a statistician.* **[1][H]**
    -   [Review (first 23) slogans](slogans23.html) **[1][S]**
15. **Data Considerations**
    -   Test-retest reliability (one of the elements of skill)
        **[2][H]**
    -   Intersubjective reliability (between subject correlation)
        **[2][S]**
    -   Recall outliers
        23. *If you torture the data long enough, it will confess to
            anything.* **[1][H]**
16. **Experimental Design**
    -   [21 Experimental Paradigms](paradigms.html) **[1][H/S]**
17. **Useful Research Tools** **+NEEDS A SUMMARY HANDOUT**
    **[1][H/S]**
    -   ORCID - research name registry **[2]**
    -   Multiple authorship issues: Contributor Roles Taxonomy
        (CRediT) - 14 elements **[3]**
    -   [Tests, instruments and batteries](instruments.html) **[2]**
        Psychological instruments: Big Five Personality Inventory,
        Interpersonal Reactivity Index (measure empathy), etc.
    -   [Useful Research Tools](tools.html)
        -   [Hearing screening inventory](hearing_screening.html)
            **[3]**
            [Coding the hearing screening
            inventory](hearing_screening_coding.html) **[3]**
        -   Ollen Musical Sophistication Index (OSMI) **[2]**
            [`http://marcs-survey.uws.edu.au/OMSI/`](http://marcs-survey.uws.edu.au/OMSI/)
            **[2]**
            [OMSI](omsi.html) **[2]**
        -   Goldsmiths Musical Sophistication Index **[2]**
        -   Montreal Battery
        -   [Humdrum Toolkit](http://musiccog.ohio-state.edu/Humdrum/)
            Music21 **[3]**
        -   Recruitment tools: `researchmatch.com` A way of recuiting
            pre-registered participants who live within a certain
            radius of some place, with certain specified skills, and
            meeting certain demographic characteristics such as age,
            sex, education, etc. **[3]**
        -   Google scholar
        -   Google scholar button - An efficient way of identify full
            references from abbreviated citations (e.g., Smith, Jones
            & Brown, 2015), and for locating PDF files of the
            corresponding works. **[2]**
        -   Zotero - Freeware for organizing references, articles,
            citations, etc. **[3]**
        -   Endnote **[3]**
        -   Word Cloud - https://wordart.com **[3]**
        -   Stackoverflow - Useful site for answering questions about
            programming. **[3]**
        -   Datathief - A useful tool for changing figures (such as
            bar graphs) back into numbers. **[3]**
        -   Linguistic Inquiry and Word Count (LIWC) project; lists of
            positive and negative words **[2]**
        -   [Subject Pool Survey](pool_survey.html) **[3]**
        -   Google n-gram, Amazon's Mechanical Turk, Google Forms,
            Qualtrics survey software, **[2]**
        -   Max-MSP **[2]**
        -   Sibelius, Finale, Verovio/Humdrum **[2]**
        -   RISM, RILM, Themefinder.org **[2]**
18. **Qualitative Methods**
    -   Participant-Observation **[2][H]**
    -   [Types of interviews](interviews.html) **[2][H]**
    -   [The Exploratory Open Interview](interviews_open.html)
        ([video](http://vimeo.com/66315146) - 45 minutes) **[2]**
        +For participant viewing alone.
    -   [Interviews in Translation](interview_trans.html) **[3]**
        +For participant reading alone.
    -   [Grounded Theory method](grounded.html) **[2][S]**
    -   [Anecdotal evidence: Uses and abuses](anecdotes.html)
        **[1][S]**
        24. *The plural of anecdote is not data.* **[1][S]**
    -   [Hypotheses - Good and Bad](hypotheses_good_bad.html)
        **[2][H]**
    -   **Group Task #18:** [Freelisting exercise](freelist_task.html)
        [(instructions)](freelist_instructions.html) **[1][H]**
    -   [Freelisting and pile sorting](freelisting.html)
        **[1][H]**
    -   [Grounded Theory - Revisited](grounded2.html) **[2][S]**
    -   Qualitative AND Quantitative **[2][H]**
19. **The Experience of Research Participants**
    -   Floor and Ceiling Effects; Use of Distractor Tasks
        **[1][S]**
    -   [An unusual ceiling case: Judging performances: sound versus
        sight](ceiling.html) **[1][S]**
    -   Primacy and recency **[1][S]**
        25. *Randomize stimuli for each participant.* **[1][S]**
    -   [Debriefing participants](debriefing.html) **[1][H]**
20. **Reading and Writing Research Articles**
    -   [Writing an empirical paper](paper.html) **[1][H]**
    -   [Citations and quotations](quotes.html) **[3][H]**
    -   [Useful Latin terms](latin.html) **[3][H]**
    -   [Critical reading of empirical articles](reading.html)
        **[2][S]**
    -   [Writing the paper first](write1st.html) **[1][H]**
        26. *Write the paper first.* **[1][S]**
    -   **Group Task #19:** Write a draft paper together
        **[1][H]**
    -   [Pre-Reviewing](prereviewing.html) **[2][S]**
21. **Potpourri**
    -   [Why experiments fail](failure.html) **[1][H]**
    -   Reserved data sets **[2][S]**
    -   [Converging evidence](converge.html) **[1][H]**
    -   [The Replication Crisis](replication.html) **[2][S]**
22. **Research Practices**
    -   Generating stimuli, MIDI, Max-MSP - demonstration
        **[3][S?]**
    -   Cultivating a Scholarly Attitude **[3][H]**
    -   [Research ethics](ethics.html) **[3][H]**
    -   Institutional Review Boards (IRB) **[2][S]**
    -   [Sample human subjects program application](IRBprogram.pdf)
        **[3][S]**
    -   [Interacting with participants](subject_interaction2.html)
        **[2][H]**
    -   Debriefing participants - demonstration **[3][H/S]**
    -   [Economics of research](economics.html) **[2][H]**
        Are there cheaper/faster/better dependent measures?
        **[2][S]**
    -   [How to revise a manuscript in response to reviewers'
        comments](revision_advice.html) **[2][H]**
    -   [How to criticize the work of others](criticism_advice.html)
        **[3][S]**
    -   [Advice when reviewing submissions](reviewing_advice.html)
        **[2][S]**
23. **Making Your Own Way**
    -   Facilities, equipment and people (people first) **[1][H]**
    -   Starting a subject pool **[1][S]**
    -   **Group Task #22:** [*Job description for research
        assistant*](research_assistant.html) **[1][H]**
    -   Review Group Task #22 - Job description for assistant. If
        these skills are so essential for your research, why don't
        you learn the pertinent skills? **[1][H]**
    -   The value of collaboration **[1][S]**
    -   Admit your ignorance (you'll learn faster) **[2][H]**
    -   Talk to a statistician before collecting data **[1][S]**
    -   **Group Task #23:** [Assess your Strengths and
        Weaknesses](strengths.html) **[1][H/S]**
24. **Final advice**
    -   Some research advice ([video](http://vimeo.com/32423934) - 12
        minutes) **[1][H]**
        27. *Nurture your passion.*
        28. *Make time to think.*
        29. *Choose projects from a long menu.*
        30. *Grow your projects.*
        31. *Knowledge is communal.*
        32. *There are no competitors, only collaborators.*
    -   [More research advice](final_advice.html) **[1][S]**
    -   [Research research](research_research.html)
        33. *Research research.* **[1][H]**
    -   [Furthering Your Education](further.html) **[2][S]**
    -   [Final review of slogans](slogans.html) (powerpoint
        presentation) **[1][H]**
    -   Music's most important discoveries lie ahead **[1][H]**
    -   [Feedback for Day 4](feedback5.html) **[1][H/S]**
    -   [Final Feedback](feedback5b.html) **[1][H/S]**

------------------------------------------------------------------------






