


[GROUP TASK #20:]{.small} Creative Thinking - SOME ANSWERS

#### Task

In the next five minutes, list as many uses as you can for a large
plastic soda bottle.

You will be graded on the number, variety, and originality of your
suggestions.

1.  something to store or carry water in
2.  a life jacket (sealed and empty, a float for bouyancy)
3.  a funnel (cut off the bottom and use the top)
4.  a toy for an infant or toddler
5.  a cup (cut off and use the bottom)
6.  a drum (strike it with sticks or hands)
7.  a whistle (blow across the top)
8.  hot water bottle (put hot water in it, and use to warm a
    sleeping bag)
9.  with frozen water, use as a food cooler
10. anchor - filled with stones (and then water) with rope attached
11. exercise weight (filled with water)
12. in windy weather, a wind-block for starting a fire (cut a
    suitably large hole in the side)

#### Rationale

Good research requires creative thinking. This task is intended to
develop your powers of associative thinking.
