


[GROUP TASK #19:]{.small} Creative Thinking

#### Task

List as many uses as you can for a large plastic soda bottle.

#### Method of Evaluation

  ----------------- --------------------------------------------------------------------------------------- ------------------------------------------------------------------------------------- ------------------------------------------------------------------------------------- ----------------------------------------------------------------
  **Criterion**     **3 points**                                                                            **2 points**                                                                          **1 points**                                                                          **0 points**
  **Fluency**       20 or more relevant responses                                                           10 to 19 relevant responses                                                           1 to 9 relevant responses                                                             No relevant responses
  **Flexibility**   14 or more different categories                                                         6-13 different categories                                                             2-5 different categories                                                              All responses in the same category
  **Originality**   At least one response that is unique or common to no more than 10% of the population.   One or more responses that are novel; common to no more than 19% of the population.   One or more responses that are slightly novel; common to 20%-49% of the population.   Responses common to 50% of the population; no novel responses.
  ----------------- --------------------------------------------------------------------------------------- ------------------------------------------------------------------------------------- ------------------------------------------------------------------------------------- ----------------------------------------------------------------

#### Rationale

Good research requires creative thinking. This task is intended to
develop your powers of associative thinking.
