

------------------------------------------------------------------------

### Criticizing Others Amicably

------------------------------------------------------------------------

"Never ascribe to malice that which can be adequately explained
by ignorance."

-Oscal Wilde (also ascribed to James Thurber)

As in any walk of life, engaging in scholarship will bring you into
contact with many people, and these contacts will inevitably lead to
the formation of both casual acquaintanceships and close
friendships. In scholarship, it is equally inevitable that you will
come to disagree with some of your fellow scholars. When writing a
book review or other scholarly paper, it is not uncommon to find
yourself disagreeing with someone whose friendship you value. Or you
may find yourself in disagreement with someone you simply don't want
to antagonize. You may struggle with the dilemma: how do I publish
critical comments while retaining an amicable relationship?

First, it is helpful to remind ourselves of the ultimate goal. As
scholars, we are all part of one big community endeavoring to
advance human knowledge.

Georg von Békésy won the Nobel Prize for his research regarding the
physiological basis for human hearing. In the Preface to von
Békésy's book, *Experiments on Hearing,* he notes that the worst
consequence of winning the Nobel Prize was that no one dared to
criticize his subsequent work. Von Békésy was acutely aware of the
importance of critics, and he lamented the fact that, after the
Nobel Prize, he had lost his best critics. As a result, he felt that
the quality of his later research suffered.

Of course in presenting our criticisms, it is important to avoid
certain pitfalls. Here are eight pieces of advice for writing
critical responses:

1.  In the media we frequently encounter stories about people who
    have perpetrated acts that are downright evil. Malicious people
    really do exist in the world. But they are extremely rare. I've
    met people who are lazy, forgetful, socially inept, misguided,
    and uninformed. But I've never met anyone who is evil.
    Especially in the world of scholarship, every one of the
    hundreds of scholars I've encountered over the decades turned
    out to be conscientious and eager to do the right thing.
    Scholars make mistakes, but I've never had any reason to doubt
    someone's integrity. Avoid thinking of someone you disagree with
    as an "enemy," a "bad person," or someone who is "sinful." Never
    ascribe to malice that which can be adequately explained by
    ignorance.
2.  Failing to be critical does not serve the aim of scholarship.
3.  Avoid hurtful language. The aim is to be critical of ideas,
    while simultaneously being supportive of the scholar.
4.  The purpose of criticism is not to "show off" your knowledge. It
    is unfortunate when a reviewer focuses on lesser or tangential
    issues as a way of demonstrating their superior knowledge.
5.  Choose your battles. It may be that there are dozens of mistakes
    and problems in a book or article. Avoid a laundry list of
    criticisms. Instead, prioritize: what are the most onerous
    issues? Focus your criticism on the ideas that have
    consequences.
6.  If you're not sure of something, don't be afraid to check with
    the author before rushing to publish. You may have misread or
    misinterpreted a passage.
7.  Always say something nice. Identify the ideas that are truly
    useful and novel. Be laudatory about the good things. In a book
    review, provide at least one sentence that gives pleasure to the
    author, and can be quoted in promotional materials for the book.
    By way of example, I am probably one of the most persistent
    critics of various ideas promoted by Dr. Carol Krumhansl. But I
    have also published the most laudatory words in print about her
    work. When Prof. Krumhansl received a lifetime achievement award
    from the Society for Music Perception and Cognition, the
    enscription was a quotation from my review of her book.
8.  Finally, after your critical remarks are published --- and when
    you next meet the author at a conference --- strike up a
    conversation. Mention the published criticism, and say that you
    hope the criticisms are taken in good faith. If an author feels
    hurt, he or she is likely to avoid you. Don't let that happen.
    Take the initiative and be friendly. Don't give animosity an
    opportunity to fester.

Notice that creating enemies and alienating people is also
antithetical to our shared scholarly goals. We need each other in
order to help us grow intellectually.

Of course, we also need to be gracious with those who are critical
of our own work. Resist the temptation to think of your critics as
competitors. The worst fate for a scholar is not that people are
critical of your work: the worse fate is that no one bothers to read
or engage with your work. As we mature as scholars, we become
increasingly thankful for a good critic. A good critic helps us
develop more quickly. And no kind word will be relished so much as
the occasional positive word from our harshest critic.




