---
title: "Day 1"
author: "David Huron"
---

1.  **Welcome & Introduction**
2.  **Generals Aims & Preview**
    -   [Day 1 Program](program1.qmd)
    -   [Learning objectives](goals.qmd)
3.  **Empirical Research**
    -   [Preamble: An Arts and Humanities Approach to Empirical
        Method](preamble.qmd)
    -   [Types of knowledge](empirical.qmd)
    -   [Seven big ideas](big_ideas.qmd)
        1.  *Motivated by truth, with no hope of proof.*
        2.  *The best research invites failure.*
        3.  *We invite failure by testing predictions.*
    -   [A line in the sand](big_ideas.qmd)
        4.  *We recognize failure by drawing a line in the sand.*
    -   [Refutation is easier than
        confirmation](big_ideas.qmd#Refutation)
        5.  *Aim not to be right, but to be not not right.*
    -   [Operationalizing](big_ideas.qmd#Operationalizing)
        6.  *Test hypotheses by operationalizing terms.*
        7.  *Operationalize, but don't essentialize.*
    -   [Comparison](big_ideas.qmd#Compare)
        8.  *Compare, compare, compare.* [Randomized Control Studies -
            The Case of Microfinance](compare.qmd)
    -   [The rhetoric of science](prophecy.qmd)
        ([video](http://vimeo.com/63377111) - 8 minutes)
        9.  *The rhetoric of science is the rhetoric of prophecy.*
            "Science is a narrative activity, conducted by a
            community of scholars who hold each other to a
            methodological commitment to making and testing
            predictions."
    -   Review the first 9 slogans: [Quiz #1](quiz1.qmd)
    -   **Group Task #1:** [What's worth knowing? An audience with
        God](god_questions.qmd)
    -   [Questions, conjectures, hypotheses and
        theories](hypotheses.qmd)
    -   **Group Task #2:** [Question, theory or
        hypothesis?](theory_hypothesis.qmd)
        [(Answers)](theory_hypothesis_answers.qmd)
    -   [Grandmother research](grandmother.qmd)
    -   [The quantitative/measurement obsession](quantitative.qmd)
    -   **Group Task #3a:** [Obvious theories - Part
        1](hindsight_task1.qmd)
    -   **Group Task #3b:** [Obvious theories - Part
        2](hindsight_task2.qmd)
    -   [(Group Task #3 Debriefing) Obvious theories: Hindsight
        bias](hindsight_task3.qmd)
        10. *Hindsight is 20/20.*
    -   [Grandmother research revisited](grandmother2.qmd)
    -   [Two forms of reductionism](reductionism.qmd)
        11. *In research, reductionism is a method, not a belief.*
        12. *Don't try to explain the whole world at once.*
    -   [Epistephobia](epistephobia.qmd)
    -   [Types of failure](truth.qmd) [(powerpoint presentation
        #3)](03_failure_types.pdf)
    -   [Review (first 12) slogans](slogans12.qmd)
4.  **Types of Empirical Studies**
    -   [Types of empirical studies](empirical2.qmd) [(powerpoint
        presentation #5)](05_empirical_studies.pdf)
    -   **Group Task #4:** [Types of studies](types.qmd)
        [(Answers/Discussion)](types_answers.qmd)
    -   [Generalizing versus universalizing](generalize.qmd)
        ([video](http://vimeo.com/66280977) - 10 minutes)
        13. *Generalize, but don't universalize.*
    -   [Exploratory studies](exploratory.qmd)
    -   [Measurement studies](measurement.qmd)
    -   [Hypothesislessness](hypothesisless.qmd)
        14. *Avoid chronic hypothesislessness.*
    -   **Group Task #5:** [Operationalize the following
        hypotheses](operationalize_this.qmd)
    -   [Syncopation: From question to hypothesis](syncopation.qmd)
    -   [Opinions as
        operationalizations](operationalize_opinions.qmd)
    -   [Double use data](double_use.qmd)
        15. *Beware of the post-hoc theory.*
    -   [Exploratory & Confirmatory: Contexts of discovery and
        legitimation (lecture)](origins.qmd)
    -   [Explore-then-test Approach](explore_then_test.qmd)
    -   [Explore-then-test example - Part 1](explore_then_test1.qmd)
        (Have a participant read the text aloud. What kind of study is
        this? What should happen next?)
    -   [Explore-then-test example - Part 2](explore_then_test2.qmd)
        (Have another participant read the text aloud. Why make use of
        a robot rather than a human?)
    -   From question ... to protocol.
        16. *From question to theory to conjecture to hypothesis to
            protocol*
    -   [Quiz #2](quiz2.qmd) [(Answers)](quiz2_answers.qmd)
    -   [Review (first 16) slogans](slogans16.qmd)
    -   [Feedback Day 1](feedback1.qmd)
5.  **Homework**
    -   *Homework 1:* [Reading: Preamble: An Arts and Humanities
        Approach to Empirical Method](preamble.qmd) *Homework 2:*
        [Reading Guide #1: Lancashire & Hirst (2009)](reading01.qmd)
    -   [Reading #1: Lancashire &
        Hirst (2009)](Agatha_Christie2009.pdf)
    -   *Homework 3:*
        **Individual Task #6:** [From question to
        theory](question2theory.qmd)

