[GROUP TASK #11:]{.small} Asymmetrical Dynamics

#### Task

Research in the field of auditory attention suggests that listeners
are more sensitive to crescendos than to diminuendos. In contrast to
diminuendos, crescendos are easier to perceive and recognize.
Gradual or long diminuendos are especially likely to escape the
listener's attention. Diminuendos are more noticeable if they are
rapid rather than gradual. This asymmetry suggests that, if a
composer wants the listener to attend to diminuendos as much as
crescendos, then the diminuendos should typically be faster
(shorter).

#### Hypothesis

In this task, we will test the hypothesis that

**H1.** *Musical diminuendos tend to be shorter than crescendos.*.

#### Operationalization

We will operationalize the terms of the hypothesis as follows:

  --------------- ------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  "diminuendos"   any hairpin diminuendo marking
  "crescendos"    any hairpin crescendo marking
  "shorter"       the horizontal length of the hairpin marking measured in centimeters; if the hairpin spans two or more systems, the summed length of the markings from start to finish
  --------------- ------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#### Sampling

For this task we will use a systematic matched-pairs sampling
method. Start in a random location in the scores ("M") section of
the Music & Dance Library. For every volume, flip to a random page
and identify the first hairpin crescendo you encounter. Measure and
record it's length. Continue *forward* through the score until you
encounter the next occurrence of a hairpin diminuendo. Measure and
record it's length. For the next volume, flip to a random page and
identify the first hairpin crescendo you encounter. Measure and
record it's length. To find it's matched pair, continue *backward*
through the score until you encounter the previous occurrence of a
hairpin diminuendo. Measure and record it's length. Alternate in
this way, moving forward and backward from random hairpin crescendos
to locate a matching hairpin diminuendo. Complete the accompanying
data sheet. Note that each crescendo should be paired with a
neighboring diminuendo.

#### Rationale

This task demonstrates that it is often possible to test theories
empirically with a minimum of technical equipment or facilities.
