

------------------------------------------------------------------------

## The Economics of Research

------------------------------------------------------------------------

Any research project is like an economic transaction: in this case,
you are "purchasing" information. Like any transaction, there are at
least four questions of interest:

1.  How much will it cost?
2.  What is the quality?
3.  When can I take delivery?
4.  Is this really what I want or need?

At the supermarket, two of these four questions are answered directly:
the price is marked on the product so there is no question about the
*cost*. Also, if you grab the product and put it in your shopping
cart, there is no question about when you can take *delivery* --- you
can take it home immediately.

The question of *quality* is more difficult. If it is something you've
purchased before, then you'll have your past experience that will help
estimate quality. If you have no past experience, choosing a
well-known brand might give you some assurance --- although *caveat
emptor* (buyer beware) still applies. You might consult with someone
who has some experience with the product and can offer some advice.

Most mysterious of all is the fourth question, *importance*: Is this
really what I want or need? How many times have you purchased
something you thought you should eat (for example), but it stayed in
your kitchen cupboards for weeks because you never really wanted to
eat it?

In contrast to supermarket shopping, purchasing information is much
more risky. All four questions are up in the air.

1.  **Cost**

    Some empirical studies can be carried out with little or no cost
    --- such as where you borrow a stack of scores from the library.
    Here the cost is principally your own time. Other studies require
    multi-million-dollar machinery (such as fMRI scanners) and
    specially-trained staff.

    There are a number of ways to handle the costs of research. These
    include: (1) *Self-funding* - Pay out of your own pocket. For
    small costs, this is often the simplest and quickest solution. (2)
    *Borrow* - Borrow equipment or facilities from others. (In the
    long run, this may make you unpopular.) (3) *Collaborate* - Join
    forces with someone who already has access to the skills,
    equipment or facilities you want. (4) *Recruit volunteers* - Find
    others willing to do the work for free. Traditionally, this has
    fallen on the shoulders of students. However, the web has provided
    new opportunities to seek the help of volunteers willing to lend a
    hand. Astronomers have very successfully recruited thousands of
    web volunteers to help with labor-intensive research tasks, such
    as classifying galaxies. There are millions of retired people
    looking for meaningful forms of volunteer work. You may need to
    pay for a research coordinator, however. (5) *Seek financial
    support* through grant applications.

    Applying for research grants can be time-consuming and
    unpredictable, so the motivation to seek funding to pay for
    high-cost research will depend on the importance of the
    anticipated results.

    By definition, research always involves something you've never
    done before. (There's no such thing as "routine research".) So
    unlike most activities, research is inherently unpredictable. Even
    if you receive a large amount of financial support, there is no
    guarantee that your question will be answered. (It's not research
    if you don't invite failure.)

2.  **Quality**

    Data vary widely in quality. EEG (brain wave) data are notoriously
    poor in quality. The important features are typically drowned-out
    by large amounts of uninterpretable noise. EEG researchers
    typically average hundreds of trials involving a dozen or more
    participants in order to glimpse any pattern in the brain waves.
    Reaction-time data are typically better quality.

    Musical scores have proved to provide remarkably high quality data
    for testing hypotheses. Unlike bored participants pushing buttons
    in an experiment, composers are often very discerning and
    deliberate when they chose one note over other possibilities. For
    example, Huron (1991) carried out a notation-based empirical study
    in which two factors were found to account for just under 90
    percent of the variance in J.S. Bach's choice of harmonic
    intervals. This is unheard of in typical psychological research
    because the collected data contain so much noise. Bach was very
    careful in his choice of harmonic intervals so it was much easier
    to decipher his principal motives.

    In general, skilled participants (like musicians) provide better
    data than unskilled participants. Children can be difficult to
    work with. Infants and non-human animals often very difficult to
    work with.

    In estimating costs, experience is the best guide. Many research
    projects are not attempted because knowledgeable researchers are
    aware that it would be difficult or impossible to collect data of
    sufficient quality.

3.  **Delivery**

    The duration of a project is often the most unpredictable part of
    research. It is common to begin a project with the expectation
    that it will take a month or two, but in the end, it might take a
    year or more. Of *cost, quality, delivery* and *importance*,
    *delivery* is commonly the most badly estimated.

4.  **Importance**

    Behavioral economists have documented a phenomenon called "buyers
    remorse." This is the feeling of disappointment a person sometimes
    experiences following a large purchase. Suppose you had $10,000.
    What would you do with it? You might consider investing it for
    your retirement. Or you might use it to purchase a new car.
    Perhaps a boat, or a round-the-world vacation with your partner,
    or maybe you'll donate the money to a worthy charity. When sitting
    on a pile of money, people take pleasure in thinking about all the
    possible things they could do with it.

    Once you spend the money, all of the possibilities "collapse" on
    just one outcome. If you purchased a new car, you might regret
    that you didn't purchase the boat you have always dreamed of. Once
    you spend the money on a world vacation, you may regret that you
    weren't more prudent by investing the money in a retirement
    account. As long as you don't spend the money, you inhabit a world
    of *possibilities* --- a world in which you can imagine having
    fun, being prudent, being virtuous, and so on. In the form of
    unspent cash, the money provides many opportunities to *dream.*

    Something similar to buyer's remorse happens with research. Once
    you select a research project and begin working on it, you lose
    some of the former freedom of thinking about all the things you
    could be doing with your time. Like spending your money, you need
    to be careful how you spend your time.

    In order to minimize "researcher's remorse" it is important not to
    pursue your first research idea. Think of several ideas, and then
    choose the one you think is the most important --- but also has a
    good chance of quick delivery, good quality results, and doesn't
    have a high cost.




