---
title: "Types of Knowledge"
author: "David Huron"
---

## Types of Knowledge

 Definition of *empirical*: knowledge gained through observation,
 experience, or experiment.

 At least three sources of knowledge can be identified:

1. *intuition* (intuitive knowledge)
2. *deduction* (deductive knowledge)
3. *observation* (empirical knowledge)

### 1. Intuition
In everyday life, the most important source of knowledge is
*intuition*.

-   The chicken salad in my refrigerator is not old, but it seems to
    smell a little odd. I decide to throw it out rather than eat it.
-   A woman is shopping for a car. She feels a vague sense of unease
    about the salesman and so decides to go to another dealership.
-   A man about to cross the street jumps back when he hears the
    sound of a car horn. The reaction is so fast, he is not even
    aware of having thought about anything.
-   A piano teacher suspects that the reason why her student is not
    progressing faster is because he is not practicing enough. She
    decides to phone his parents.

Some of our intuitions have been shaped by millions of years of
evolution --- and are designed to save our lives. We become
suspicious for reasons which elude us.

Especially in matters related to music-making, the most important
knowledge we have is probably intuitive knowledge. Without
intuition, music-making would be impossible.

### 2. Deductive

Deductive knowledge is also called *rationality*. Deductive
knowledge arises from logical thought.

-   If all people are mortal, and Socrates is a person, then
    Socrates is mortal.
-   Seeing a guitarist move her finger one fret toward the tone
    hole, we conclude that the next pitch will be one semitone
    higher than the previous pitch.
-   The first 8 pages of a Beethoven manuscript are written using a
    dark blue ink. The remaining 11 pages in the manuscript use a
    more purple-colored ink. An accompaniment figuration for a
    phrase near the beginning of the work is written using the
    purple ink. If we assume that the purple ink was used after
    exhausting the dark blue ink, it follows that the accompaniment
    must have been added after the melody line was written.

### 3. Empirical

Empirical knowledge is knowledge gained through observation.
Observation may occur informally, or we may create a formal plan for
observation. An example of informal observation is what we call
"experience." An example of formal observation is an "experiment."
So we can rephrase our definition as: Empirical knowledge is
knowledge gained through observation, experience, or experiment.

-   I know that many birds are capable of flight because I see them
    fly.
-   I've observed that some musicians can always identify the names
    of pitches ("perfect pitch") and others can't.
-   I have witnessed only a couple of occasions when people dance
    without music: People rarely dance without music.
-   I know that some music can send shivers up my spine because I
    have experienced this.
-   I know that works for xylophone are much more likely to be in
    the major mode than works for marimba because I've examined (and
    counted) a large number of works for xylophone and marimba.

 Intuitive, deductive and empirical forms of knowledge are all
 necessary for life. Each form of knowledge adds to the value of the
 others. That is, they are complementary forms of knowledge.

 In addition, each form of knowledge also has limitations. There are
 times when our intuitions prove to be wrongheaded. For example, a
 child's intuition may tell him not to let a nurse stick a needle into
 his arm--even though an inoculation will help prevent illness.
 Here, intuition fails us. There are many situations when rational
 deduction proves to be impossibly complicated or time-consuming. For
 example, when identifying the pros and cons of purchasing a particular
 house, we may find it impossible to "calculate" all of the pertinent
 factors. Here, rational deduction fails us. Regularly watching the
 local television news, an elderly woman may conclude that her
 neighborhood is full of crime, and that she should refrain from going
 outside for her daily walk. Here, observation fails us.