---
title: "Epistephobia"
author: "David Huron"
---

# Epistephobia



> "... he that increaseth knowledge, increaseth sorrow." - Ecclesiastes
1:18

## Fear of Knowing

Attempts to account for sublime experiences of music will inevitably
be disappointing because they trivialize the profound. For example,
biologists tell us that "love" is nature's way of promoting
pair-bonding and procreation. This may be biologically true, but it
captures none of the beauty, power, and deep meaning we experience
through love.

It is perfectly reasonable for a person to say "I don't want to know
about that." "I don't want to know how music works."

However, curiosity is also a deeply human characteristic. It is
perfectly reasonable for a person to say "I *want* to know about
that." "I *want* to know how music works."

A common complaint is that science contributes to the
"demystification" of the world. That is, knowledge makes the world
less rich, less compelling, less magical, or less beautiful.

However, consider the case of modern astronomy. In ancient times,
people looked up into the sky and saw all sort of mythical objects
and creatures. They thought that the movement of the planets
affected human behavior on earth. Modern astronomy seems to have
discarded these colorful and rich ideas. But modern astronomy
replaced the stories of the heavens with a different set of stories:
of enormous objects at unfathomable distances, of quasars and
galaxies, of black holes and big bangs. Can we really say that the
stories provided by modern astronomy are less compelling, magical,
or beautiful than Medieval beliefs about the heavens?

Another point of view comes from the world of theatrical magic. The
famed broadway magician, Doug Henning, suggested that only the
magician gets to see the true magic. Theatrical magic involves
ordinary manipulation of physical objects, but done in a way that
leaves viewers astonished. For the magician, there is nothing
mystical about the physical objects or their manipulation: the real
mystery resides in the fact that viewers can be astonished.
Similarly, music is just sound --- the physical jiggling of air
molecules. What is astonishing is not the sound, but what it evokes
in listeners. Part of understanding the magic of music, is realizing
the extraordinarily pedistrian nature of sound. Like the magician,
stripping away the mystification may be the first step in allowing
us to see the true magic of music.

Finally, if you are worried that knowledge might somehow destroy
your love of music, you may find consolation in the idea that nearly
all theories are wrong. Even with the best research efforts, musical
probably doesn't work the way we think it works.

If you are truly afraid that knowledge might spoil your experience
of music, then don't engage in music research.




