

------------------------------------------------------------------------

### Research Ethics (Lecture notes)

------------------------------------------------------------------------

1.  **Nazi Medical Experiments.** Nazi doctors: the only direct
    measures of blood pressure.
2.  **Nuremberg Trials.** In the aftermath of the second World War, 23
    doctors were put on trial at Nuremberg. Unlike the other Nuremberg
    trials, only the US was involve in prosecutions.
3.  **Nuremberg Code.** Ten points. For our purposes, three main
    points: The first point is that voluntary consent of the human
    subject is absolutely essential. Second: that physical and mental
    suffering should be minimized. And third: The degree of risk to be
    taken should never exceed that determined by the humanitarian
    importance of the problem to be solved by the experiment.
4.  **Tuskegee syphilis experiment.** Was conducted in Macon County,
    Alabama between 1932 and 1972. Was an official U.S. government
    experiment conducted by the U.S. Public Health Service. Involved
    600 African American sharecroppers - 399 had contracted syphilis
    before the study began, and another 201 were recruited as
    controls. As a recruitment incentive, the men were provided with
    free medical care, meals, and free burial insurance. None were
    told that they had syphilis. By 1940, medical science had well
    established that penicillin is an effective treatment for
    syphilis. Nevertheless, the researchers wanted to chronicle the
    natural progression of the disease. None of the men were ever
    treated. The experiment stopped in 1972, only because of a
    whistleblower. Notice that the research was government sponsored,
    and continued 25 years after the establishment of the Nuremberg
    Code.
5.  **Helsinki Declaration (1964).** Several revisions (the most
    recent, 2013). Major revision in 1974 --- partly instigated by
    public revelation of the Tuskegee syphilis experiment.
6.  **Japanese Chemical Weapons Experiments in Manchuria.** None of
    the Japanese researchers involved were prosecuted. The U.S.
    government made a deal with the Japanese: they would not prosecute
    if the Japanese turned over all of their research results to the
    U.S. military.
7.  **Research Fraud.** Apart from treatment of human and animal
    participants, research ethics also embraces other aspects of
    research conduct. Many cases of research fraud including (1)
    making up data (or tampering with data) [recent case of Prof.
    Mark Hauser at MIT - he lost his job]; (2) stealing or failing to
    acknowledge origin of research ideas; (3) improper authorship
    attribution [for multi-authored papers, many science journals now
    require a letter or document describing in detail which author was
    responsible for which aspect of the research; some journals
    **publish** this information as a footnote in the published
    article.]
8.  **What constitutes research with human subjects?** The regulations
    were drawn up by people in medicine, with no consideration for
    arts and humanities scholarship. E.g., interviewing a person [My
    experience with Johan Sundberg's visit to OSU. Applied for
    exemption 2 weeks before visit; wasn't processed in time for the
    interview.] E.g.2: Examining past (non-public) historical records
    of anyone who is still living.
9.  **Educational Exemption.** Educators were savvy and got an
    exemption. Any research related to curriculum development or
    educational testing is exempt from any human subjects review.
10. **The Arts and Humanities are not impervious to the Dark Side.**
    Charge of plagarism: if unfounded, has a negative impact on a
    composer's reputation; if the composer is alive, then the moral
    consequences are amplified. E.g., the "dark days" of Comparative
    Musicology - the Great Chain of Being. Music as representative of
    different stages in human development: hunter/gathers,
    agrarian/tribal, urban/democratic.
11. **Take-home Message.** It is important to treat people well.
