---
title: "Explore then Test, part 2"
author: "David Huron"
---

# Who's Trustworthy? A Robot Can Help Teach Us

By Tara Parker-Pope *New York Times* September 10, 2012, 8:10 PM

[continuation of the article]

The researchers then conducted an experiment pairing students with a
friendly-faced robot, developed by Cynthia Breazeal, who directs
M.I.T.'s personal robots group.

The setup was basically the same, except the students had a 10-minute
conversation with the robot before they played the game. (The extra
time was needed to help the student get over the "wow" factor of
talking to a robot.) A woman acted as the robot's voice, but she was
unaware of its movements, which were controlled by two other people.
Sometimes the robot used only typical gestures, like moving a hand or
shrugging its shoulders, but sometimes it mimicked the four cues of
distrust: clasping its hands, crossing its arms, touching its face or
leaning away.

Surprisingly, when students saw the robot make the hand and body
gestures associated with distrust, they later made decisions in the
token game that suggested they didn't trust the robot.

In questionnaires afterward, students in both groups rated the robot
equally likable. But those who had unknowingly witnessed the cues
associated with distrust also rated the robot as less trustworthy,
compared with students exposed to only the conversational gestures.

"It makes no sense to ascribe intentions to a robot," said an author
of the study, Robert H. Frank, an economics professor at Cornell. "But
it appears we have certain postures and gestures that we interpret in
certain ways. When we see them, whether it's a robot or a human, we're
affected by it, because of the pattern it evokes in our brain
responses." Dr. Frank said the study suggested that there might have
been an evolutionary benefit to cooperation --- and, more important,
to the ability to determine who could be trusted.

[N.B. A video of the robot making untrustworthy gestures can be found
at:
<http://well.blogs.nytimes.com/2012/09/10/whos-trustworthy-a-robot-can-help-teach-us/?ref=health]




