

------------------------------------------------------------------------

### Exploratory Studies

------------------------------------------------------------------------

The emphasis in exploratory research is observation. At the same time,
researchers anticipate that the exploratory observations will lead to
new *questions*, and these questions will, in turn, lead to the
development of explanatory *theories* or *interpretations*.

With regard to observation, the observer can often choose to be either
visible or invisible. The invisible observer lurks in the background
like the proverbial "fly-on-the-wall," hoping not to influence or
change what is going on. In most studies of animal behavior, the
ethologist tries to observe clandestinely. For example, an
ornithologist might build a *blind* in order to hide her/his presence.
For some animal species, hiding may be entirely successful. However,
for other species, it may prove impossible to disguise your presence.
Bonobos and chimpanzees, for example, are far too attentive and
curious to allow a researcher to observe them in the wild without
their awareness.

Technology often allows effective clandestine observation. For
example, in a study of audience behavior, Olaf Post made use of video
recordings made from security cameras in the Amsterdam Concertgebouw
concert hall. This allowed Post to observe members of the audience
with minimal influence. Written documents can provide similar
opportuities for "invisible" observation: when a theorist examines a
published score, the observations made will have little or no impact
on the behavior of the composer who created the score.

At the other extreme, the researcher may choose to observe "from the
inside" rather than from the outside. In this case, the researcher
aims to learn through active participation. The best-known example of
this approach is the *participant-observation* method commonly used in
anthropology and ethnomusicology. For example, a researcher might lean
to play the *rebab* as a way to better understand Moroccan Berber
music. Many important observations are introspective---recognizing
what it feels like to dance, play an instrument, or be disciplined by
a master teacher.

An unusual cross-species example of participant-observation involved
musician Peter Gabriel working at the Great Ape Trust in Iowa. Gabriel
improvized music---taking his lead from the music produced by Kanzi, a
chimpanzee. The interactions were recorded on video.

There are advantages and disadvantages associated with each approach.

In some cases, artificial environments can be constructed to aid
observation. In animal behavior, an ant colony might be created in a
laboratory, with suitable use of glass and cameras to facilitate
observation. In other cases, an artificial environment may be created
in which humans interact closely with the observed individual. Close
interaction between researcher and animal may occur. For example, the
gorilla, Koko, was raised in a human family-like environment. It is
often too dangerous for a researcher to attempt to fit-in with some
animal group.

Of course exploratory studies can also be done from the comfort of
your own home. You might search the Internet for the phrases like "I
love bluegrass" or "I hate music" as a way of exposing yourself to
commentaries, opinions, or viewpoints representative of different
communities or subcultures whose experiences differ from your own. In
some cases, researchers have posed (online) as a member of a group, in
order to provoke responses---such as asking questions.

As noted, in exploratory research, one hopes that the observations
will inspire the researcher into posing new questions. Observation may
lead to questions such as:

1.  Why is reggae so popular among Pacific island cultures?
2.  Why do people tap their feet while listening to music? Why don't
    people shake their elbows instead?
3.  Why are pianos and guitars more popular instruments than (say)
    bagpipes and ocarinas?
4.  Why do young musicians in Pohnepei dress and speak like they are
    African-Americans?
5.  Why is music so repetitive?
6.  Why do people willingly listen to music that makes them sad?
7.  Why are people nostalgic for the music they heard during their
    teens? Is this true around the world?
8.  Why is American blues so popular in Russia?
9.  Why is opera so polarizing? People either seem to love it or hate
    it.
10. Why has Chinese music remained unpopular outside of China, but
    Chinese food is popular all around the globe?
11. Why do tunes get stuck in your head?

Good questions should, in turn, begin the process of theory formation.
A good exploratory study may end by proposing a possible explanatory
theory. However, any resulting theory is *post hoc* and so is regarded
as empirically weak. The observations cannot be viewed as "supporting"
or "testing" the theory, since the observations were the inspiration
for the theory in the first place.

Exploratory research should not be considered "passive." First,
observation itself may involve extraordinary effort in order to be in
a position to observe. A researcher may travel to a remote corner of
the world (or even to another planet), simply to observe something. In
addition, observation sometimes requires you to do things that are
outside of your "comfort zone." If you are Christian, you might
consider visiting a mosque or a Hindu temple. If you are Moslem, you
might attend a synagogue or a *pow-wow*.

#### Reference

Olaf Post (2009). *"The way these people can just listen!": Inquiries
about the Mahler tradition in the Concertgebouw.* PhD dissertation,
Columbia University.
