

------------------------------------------------------------------------

## Who's Trustworthy?

------------------------------------------------------------------------

By Tara Parker-Pope *New York Times* September 10, 2012, 8:10 PM

How do we decide whether to trust somebody?

While many people assume that behaviors like avoiding eye contact and
fidgeting are signals that a person is being dishonest, scientists
have found that no single gesture or expression consistently predicts
trustworthiness.

But researchers from Northeastern University, the Massachusetts
Institute of Technology and Cornell recently identified four distinct
behaviors that, together, appear to warn our brains that a person
can't be trusted.

The findings, to be published this month in the journal *Psychological
Science*, may help explain why we are sometimes quick to like or
dislike a person we have just met. More important, the research could
one day be used to develop computer programs that can rapidly assess
behavior in airports or elsewhere to flag security risks.

In the experiment, 86 undergraduates from Northeastern were given five
minutes to get to know a fellow student they hadn't met before. Half
the pairs met face to face; the other half interacted online by
instant message.

Then the students were asked to play a game in which all the players
got four tokens and the chance to win money. A token was worth $1 if
a player kept it for himself or $2 when he gave it to his partner.
Players could win $4 each if both partners kept their tokens, but if
they worked together and traded all four tokens, then each partner
could win $8. But the biggest gain --- $12 --- came from cheating a
partner out of his tokens and not giving any in return.

Over all, only about 1 in 5 people (22 percent) were completely
trustworthy and cooperative, giving away all their tokens so that each
partner could win $8. Thirteen percent were untrustworthy, keeping
all or most of their tokens. The remaining 65 percent were somewhat
cooperative, giving away two or three tokens but also holding one or
two back for security.

Both groups demonstrated the same level of cooperation. Whether the
students met face to face or online didn't change their decisions
about how many tokens to give away or keep. But students who met in
person were far better at predicting the trustworthiness of the
partner; that suggested they were relying on visual cues.

"Lack of face-to-face contact didn't make people more selfish," said
the study's lead author, David DeSteno, a professor of psychology at
Northeastern. "But a person's ability to predict what their partner
was going to do was greater face to face than online. There is
something the mind is picking up that gives you greater accuracy and
makes you better able to identify people who are going to be
trustworthy."

To find out what cues the players were responding to, the researchers
filmed the students' five-minute conversations before the game
started. They discovered that four specific gestures predicted when a
person was less trustworthy: leaning away from someone; crossing arms
in a blocking fashion; touching, rubbing or grasping hands together;
and touching oneself on the face, abdomen or elsewhere. These cues
were not predictive by themselves; they predicted untrustworthiness
only in combination.

And individuals intuitively picked up on the cues. "The more you saw
someone do this, the more intuition you had that they would be less
trustworthy," Dr. DeSteno said.

"Life is all about finding people you can trust in different
situations."




