---
title: Factor Analysis
author: David Huron
---

Factor analysis is a statistical method that can be used to reduce
or distill many variables into a smaller number of variables (called
*factors*). Many variables are highly correlated, and this suggests
that there is an underlying cause responsible for the similar
behavior of correlated variables. This unobserved variable can be
regarded as "latent" in the data. The purpose of factor analysis is
to expose or reveal possible latent variables.

An example of the use of factor analysis is found in a study by
Thomas Schäfer and Peter Sedlmeier (2009). They asked 507 Germans to
rate how well they liked 25 musical styles. Of course people have
different preferences: Some people like classical music, some like
jazz, and some like rock. But it is not simply the case that people
like one style and are indifferent to other styles. For example, a
person might most prefer jazz, but also enjoy reggae. It turns out
that there are broad patterns evident in people's likes and
dislikes. For example, a person who likes *goth* is also likely to
enjoy *punk* and *metal*. People who like *gospel* also tend to
enjoy *soul.* People who like *folk* music are more likely than
other people to enjoy *country* music. Factor analysis uses the
correlations between different variables to reduce the number of
independently varying qualities.

In their factor analysis of stylistic preferences, Schäfer and
Sedlmeier found an underlying commonality was between *techno*,
*trance*, *dance* and *house*. Whatever it is that causes a person
to like any one of these also tends to dispose that person to like
the others as well. In other words, factor analysis suggests a
common cause that leads to a preference for all four styles.

The table below identifies the so-called factor "loadings" for 25
musical styles on the six dimensions arising from the factor
analysis carried out by Schäfer and Sedlmeier.

  Style                Sophisticated   Electronic   Rock      Rap       Pop       Beat, folk, & country
  -------------------- --------------- ------------ --------- --------- --------- -----------------------
  **Jazz**             **.81**                                                    
  **Blues**            **.77**                                                    
  **Swing**            **.70**                                                    
  **Classical**        **.69**                                                    
  **Techno**                           **.88**                                    
  **Trance**                           **.87**                                    
  **House**                            **.77**                                    
  **Dance**                            **.71**                                    
  **Punk**                                          **.77**                       
  **Metal**                                         **.70**                       
  **Rock**                                          **.67**                       
  **Alternative**                                   **.66**                       
  **Gothic**                                        **.56**                       
  **Ska**                                           **.54**                       
  **Hip hop**                                                 **.73**             
  **Rap**                                                     **.71**             
  **Reggae**                                                  **.66**             
  **Pop**                                                               **.82**   
  **Soul**                                                              **.64**   
  **Rhythm & Blues**                                                    **.63**   
  **Gospel**                                                            **.55**   
  **Beat music**                                                                  **.69**
  **Folk**                                                                        **.67**
  **Country**                                                                     **.67**
  **Rock & roll**                                                                 **(.46)**

Notice that the factor analysis points to an underlying commonality
between *jazz*, *blues*, *swing* and *classical*. It is important to
understand that these styles are not a "cluster." They are simply
the variables that exhibit the greatest "loading" on the proposed
factor. Other likes & dislikes may contribute to this factor, but
these four contribute the most. It's also important to note that not
everyone will share the same constellation of tastes. For example,
not everyone who enjoys *jazz* will enjoy *classical,* and vice
versa. Instead, there is an underlying "something" that seems to
encourage people to like *jazz, blues, swing* and *classical,* more
than other styles. Notice that *jazz* (.81) and *blues* (.77) load
on this factor more than *swing* (.70) and *classical* (.66).

Instead of refering to a factor as "Factor 1" or "Factor 2," it is
often helpful to refer to a factor by giving it a name. For example,
Schäfer and Sedlmeier, decided to refer to the first factor using
the name "sophisticated." Similarly, they decided to refer to the
second factor (with high loadings on techno/trance/dance/house)
using the term "electronic." It is important to understand that
these names are interpretations offered by the researcher, and that
there is no official status to these labels. Other researchers may
disagree with a factor name, and in some cases the name may be
deceptive or reflect researcher bias. For example, one could argue
that the jazz/blues/swing/classical factor might be better labelled
"born before 1960," while the punk/metal/rock/alternative/gothic/ska
factor might be better labelled "born between 1965 and 1980." Factor
analysis does not tell you the source or reason for the underlying
factor; it simply indicates that such a factor probably exists.

It is important to understand that factor analysis doesn't simply
discard some of the original variables. In Schäfer and Sedlmeier's
analysis of styles, the factor analysis is not merely a way to
reduce the number of styles. The styles may be truly distinct, and
one style can't simply be regarded as a "variant" of some other
style. Instead, the underlying factors may relate to entirely
different phenomena. For example, the factors accounting for
stylistic preferences might relate to age, race, geography, or
parental educational attainment. Factor analysis doesn't mean that
*soul* and *rhythm & blues* are similar. It means that whatever
causes a person to like *soul* is similar to whatever causes a
person to like *rhythm & blues.* Similarly, a liking for *jazz*
shares some underlying cause with a liking for *classical*
music---even though the styles are clearly different.

Factor analysis is similar to another statistical method known as
*Principal Components Analysis* (PCA). The two methods use different
numerical methods, but share many commonalities. An important
difference between PCA and factor analysis is that factor analysis
can also be used to test an *a priori* theory. Suppose, for example,
that you have a theory that there are four factors contributing to
the quality of a musical performance. Factor analysis can be used to
*test* your theory, determining the probability that the
observational data are consistent with the four proposed factors. So
in addition to providing a method for exploratory data analysis,
factor analysis can also be used as an inferential test---a way of
testing a prior hypothesis.

#### References

Thomas Schäfer and Peter Sedlmeier (2009). From the functions of
music to music preference. *Psychology of Music,* Vol 37, No. 3, pp.
279-300.

Thomas Schäfer, Peter Sedlmeier, Christine Städtler and David Huron
(2013). The psychological functions of music listening. *Frontiers
in Psychology,* Vol 4, No. 511, pp. 1-33. DOI:
10.3389/fpsyg.2013.00511
