

------------------------------------------------------------------------

### Failure

------------------------------------------------------------------------

Part of doing research involves living with failure. (Remember, *The
best research invites failure.*) Ideally, research projects fail for
the *right* reasons: The best reason for a project to fail is that the
hypothesis is wrong and you need to think differently about your
problem. Unfortunately, there are many other reasons why a project can
fail. It may be that your hypothesis is correct and the failure has a
different origin.

When you experience a research failure, it's appropriate to spend some
time thinking about possible reasons for the failure. Usually, it is
impossible to determine *why* a project failed. However, in some cases
the source of the failure is identifiable.

First, why do hypotheses fail?

-   Because the hypothesis is wrong.
-   Because the population was incorrectly identified.
-   Because the sample was biased and so not representative of the
    population.
-   Because the sample size was too small.
-   Because the effect size is small.
-   Because the operationalized measures are poor approximations of
    the theoretical terms.
-   Because of a calculation or tabulation error.
-   Because the control group is biased.
-   Because an unidentified third variable is influencing the results.
-   Because the task was too easy (i.e., *ceiling effect*).
-   Because the task is too hard or the participants are unskilled
    (i.e., *floor effect*).
-   Because the participants didn't try (also leading to a *floor
    effect*).
-   Because of some demand characteristic that is causing participants
    to undermine the hypothesis.

Why do research projects fail?

-   Because you can't get a piece of equipment, or because of
    equipment failure.
-   Because you have difficulty recruiting appropriate participants.
-   Because you run out of time.
-   Because the cost of the project exceeds your budget.
-   Because your original goal was too ambitious.
-   Because a collaborator didn't contribute as anticipated.
-   Because you lost your passion or enthusiasm.




