

### Feedback - Workshop Goals

The workshop aimed to achieve nine specific goals. For each goal,
indicate how well you think the workshop succeeded.

1.  To communicate the main concepts and techniques in modern
    empirical research.
      ----------- ------ ------ ------ -----------
      very poor   poor   okay   well   very well
      ----------- ------ ------ ------ -----------
2.  To provide practical experience in research skills, including
    posing research questions, formulating and operationalizing
    hypotheses, designing experiments and questionnaires, and
    analyzing data.
      ----------- ------ ------ ------ -----------
      very poor   poor   okay   well   very well
      ----------- ------ ------ ------ -----------
3.  To provide practical research advice.
      ----------- ------ ------ ------ -----------
      very poor   poor   okay   well   very well
      ----------- ------ ------ ------ -----------
4.  To expose participants to examples of empirical music studies
    through lectures and readings.
      ----------- ------ ------ ------ -----------
      very poor   poor   okay   well   very well
      ----------- ------ ------ ------ -----------
5.  To build critical skills when reading empirical research studies
    --- identifying both strengths and weaknesses.
      ----------- ------ ------ ------ -----------
      very poor   poor   okay   well   very well
      ----------- ------ ------ ------ -----------
6.  To stimulate participants' creative imaginations in posing and
    pursuing musical questions.
      ----------- ------ ------ ------ -----------
      very poor   poor   okay   well   very well
      ----------- ------ ------ ------ -----------
7.  To provide sufficient background so that participants will feel
    confident in beginning their own program of empirical music
    research.
      ----------- ------ ------ ------ -----------
      very poor   poor   okay   well   very well
      ----------- ------ ------ ------ -----------
8.  To identify resources for continuing education in empirical
    musicology.
      ----------- ------ ------ ------ -----------
      very poor   poor   okay   well   very well
      ----------- ------ ------ ------ -----------

    
    
9.  To offer a philosophical framework for understanding how empirical
    methods can be contextualized within traditional concerns in the
    arts and humanities.
      ----------- ------ ------ ------ -----------
      very poor   poor   okay   well   very well
      ----------- ------ ------ ------ -----------


What goal(s) would you like to see added to the workshop aims?




