

------------------------------------------------------------------------

### Feedback - Day 1

------------------------------------------------------------------------

1.  First, tell us about the speed or *pacing* of the workshop:
    -   too slow
    -   a bit slow
    -   about right
    -   a bit fast
    -   too fast
2.  Second, tell us about the *level of difficulty*. Overall, I find
    the workshop material:
    -   too easy
    -   a bit easy
    -   about right
    -   a bit challenging
    -   somewhat challenging
    -   too hard
3.  How useful was each group activity? (Circle 1, 2 or 3 stars ---
    where three stars is best.)
    -   [[★ ★ ★]{.small}]{.small} What's worth knowing? An audience
        with God.
    -   [[★ ★ ★]{.small}]{.small} Classifying statements as
        *questions, theories, conjectures* or *hypotheses*.
    -   [[★ ★ ★]{.small}]{.small} Hindsight bias - interpreting
        results from the *American Soldier* study
    -   [[★ ★ ★]{.small}]{.small} Types of empirical studies -
        *Descriptive, Correlational, Experimental*, etc.
    -   [[★ ★ ★]{.small}]{.small} Operationalizing: e.g. Women like to
        dance more than men.
4.  Overall, I found the group activities:
    -   of limited use
    -   okay
    -   useful
    -   very useful
5.  Tell us the most important thing you learned today.
    
    
    
    
    
6.  Of all the material we covered today, the least useful topic was:
    
    
    
    
    
7.  General suggestions (on reverse):
