

------------------------------------------------------------------------

### Feedback - Day 3

------------------------------------------------------------------------

1.  First, tell us about the speed or *pacing* of today's workshop:
    -   too slow
    -   a bit slow
    -   about right
    -   a bit fast
    -   too fast
2.  Second, tell us about the *level of difficulty*. Overall, I found
    today's workshop material:
    -   too easy
    -   a bit easy
    -   about right
    -   a bit challenging
    -   somewhat challenging
    -   too hard
3.  How useful was each topic? (Circle 1, 2 or 3 stars --- where three
    stars is best.)
    -   [[★ ★ ★]{.small}]{.small} Descriptive statistics
    -   [[★ ★ ★]{.small}]{.small} Null hypothesis
    -   [[★ ★ ★]{.small}]{.small} Confidence level
    -   [[★ ★ ★]{.small}]{.small} Statistical significance
    -   [[★ ★ ★]{.small}]{.small} Chi-square test
    -   [[★ ★ ★]{.small}]{.small} Multiple tests
    -   [[★ ★ ★]{.small}]{.small} Daniel Shanahan's lecture
    -   [[★ ★ ★]{.small}]{.small} Advanced statistics (cluster
        analysis, factory analysis, MDS)
    -   [[★ ★ ★]{.small}]{.small} Discussion of Perttu (2007) reading
4.  Overall, I found today's group activities:
    -   of limited use
    -   okay
    -   useful
    -   very useful
5.  Tell us the most important thing you learned today.
    
    
    
    
    
6.  Of all the material we covered today, the least useful topic was:
    
    
    
    
    
7.  General suggestions (on reverse):
