

### Feedback - Final

1.  Please help us by assessing the relative value of the main topic
    units in the workshop:
      ----------------------------------------------- ------------- ------ -------- ------------- -----------
      **Empirical knowledge**                         less useful   okay   useful   very useful   essential
      **Inviting failure**                            less useful   okay   useful   very useful   essential
      **Line-in-the-sand**                            less useful   okay   useful   very useful   essential
      **Rhetoric of science**                         less useful   okay   useful   very useful   essential
      **Questions/Conjectures/Hypotheses/Theories**   less useful   okay   useful   very useful   essential
      **Grandmother research**                        less useful   okay   useful   very useful   essential
      **American solider (hindsight bias)**           less useful   okay   useful   very useful   essential
      **Reductionism**                                less useful   okay   useful   very useful   essential
      **Type I & II errors**                          less useful   okay   useful   very useful   essential
      **Hypothesislessness**                          less useful   okay   useful   very useful   essential
      **Operationalizing hypotheses**                 less useful   okay   useful   very useful   essential
      **Explore-then-test**                           less useful   okay   useful   very useful   essential
      **From Question to ... to Protocol**           less useful   okay   useful   very useful   essential
      **Causation & manipulation**                    less useful   okay   useful   very useful   essential
      **Sampling methods & problems**                 less useful   okay   useful   very useful   essential
      **Data Independence**                           less useful   okay   useful   very useful   essential
      **Correlation demo**                            less useful   okay   useful   very useful   essential
      **Regression-to-the-mean**                      less useful   okay   useful   very useful   essential
      **Demand characteristics**                      less useful   okay   useful   very useful   essential
      **Measurement scales**                          less useful   okay   useful   very useful   essential
      **Questionnaires**                              less useful   okay   useful   very useful   essential
      **Reading: Agatha Christie**                    less useful   okay   useful   very useful   essential
      **Reading: Dan Perttu**                         less useful   okay   useful   very useful   essential
      **Statistics**                                  less useful   okay   useful   very useful   essential
      **Chi-square test**                             less useful   okay   useful   very useful   essential
      **Multiple tests**                              less useful   okay   useful   very useful   essential
      **File drawer effect**                          less useful   okay   useful   very useful   essential
      **Research instruments**                        less useful   okay   useful   very useful   essential
      **Interacting with subjects**                   less useful   okay   useful   very useful   essential
      **Writing empirical paper**                     less useful   okay   useful   very useful   essential
      **Writing the paper first**                     less useful   okay   useful   very useful   essential
      **Why experiments fail**                        less useful   okay   useful   very useful   essential
      **Final advice**                                less useful   okay   useful   very useful   essential
      ----------------------------------------------- ------------- ------ -------- ------------- -----------
2.  What topic(s) would you like to see added to the workshop
    curriculum?
    
    
    
    
3.  Tell us about the four-day duration of the workshop:
      ----------- ------------- ----------
      too short   about right   too long
      ----------- ------------- ----------
4.  Tell us about the scheduling: Were the start and end times okay?
    The number and duration of the breaks, the time allotted for
    lunch, etc.
    
    
    
    
5.  Tell us about the group exercises:
      --------- ------------- ----------
      too few   about right   too many
      --------- ------------- ----------
6.  Would you have liked more homework, or did you prefer the free
    evenings?
      --------------- ------------- ---------------
      more homework   about right   less homework
      --------------- ------------- ---------------
7.  Tell us about the guest presentation by Joshua Albrecht.
    
    
    
    
8.  What was the least-good thing about the workshop?
    
    
    
    
9.  What was the best thing about the workshop?
    
    
    
    
10. How did you learn about the workshop?
    
    
    
    
11. Would you recommend the workshop to your colleagues?
    
    
    
    
12. General comments:
