

------------------------------------------------------------------------

### Feedback - Presenter

------------------------------------------------------------------------

The aim of this feedback is to evaluate the workshop presenter (rather
than the workshop content).

1.  How well did the instructor *communicate the workshop objectives*
    at the beginning?
    -   not very well
    -   okay
    -   well
    -   very well
2.  How successful was the instructor in *achieving* the workshop
    objectives?
    -   not very successful
    -   okay
    -   successful
    -   very successful
3.  How *knowledgeable* was the instructor of the subject matter?
    -   not very knowledgeable
    -   okay
    -   knowledgeable
    -   very knowledgeable
4.  How *organized* was the instructor?
    -   not very organized
    -   okay
    -   organized
    -   very organized
5.  How *clear* was the communication?
    -   not very clear
    -   okay
    -   clear
    -   very clear
6.  How *responsive* was the instructor to participants' questions
    and comments?
    -   not very responsive
    -   okay
    -   responsive
    -   very responsive
7.  How well did the instructor *motivate or inspire* you to learn?
    -   not very motivating
    -   okay
    -   motivating
    -   very motivating
8.  Suggestions for improvement:
    
    
    
    
    
    
