


[GROUP TASK #18:]{.small} Free Listing Instructions

#### Task

I'm going to ask you to make a list of a certain sort. You will be
given just sixty seconds to perform this task. Your aim should be to
make the list as long as you can in the short time provided. Wait
for verbal instructions before you start.

VERBAL INSTRUCTION: In the next 60 seconds, I want you to list as
many composer's names as you can. Go.

After the alotted time has elapsed, call for a stop.

First, check to see if you have any duplicated names; if so, scratch
out the **second** occurrence of that name.

Have participants number the names beginning at the **end** of the
list with the number 1.

Did anyone get as many as twenty names? (That would be
extraordinary.) Who got the most number of names (congratulations to
the winner!).

Ask for a volunteer. Have the assistant tally the total numbers for
all names mentioned more than once: E.g., Beethoven:
20+21+13+18+...; etc. Probable:

1.  Beethoven
2.  Mozart
3.  Bach
4.  Haydn
5.  Schubert
6.  Brahms
7.  Mendelssohn
8.  Handel
9.  Chopin
10. Liszt
11. Mahler
12. Tchaikovsy
13. Ravel
14. Stravinsky
15. Wagner
16. Vivaldi
17. Schumann
18. Debussy
