


------------------------------------------------------------------------

## Freelisting and Pile Sorting

------------------------------------------------------------------------



"The freelist is, I believe, the single most powerful and
informative systematic data-collection technique available,
because it is easy to use; you don't need many informants; and it
offers a powerful emic snapshot of the *cultural domain* that you
are interested in studying."

- Victor De Munck (2009, p.47)

Freelisting and pile sorting are exploratory research methods
intended to give a quick overview of some domain of human thought
within a cultural context. They are usually used when a researcher
first explores a cultural phenomenon. For example, a researcher
might be interested in how people in some culture conceive of foods
and food preparation, or a scholar might be interested in how people
distinguish different forms of dance.

#### Freelisting

Freelisting typically involves brief interviews with a relatively
small number of informants. The interview consists of posing a
question of the form: "What's sorts of *X* are there?" Or: "List all
the *X*s you know." Sample freelist instructions might include the
following:

List all the colors you know.
What are bad things a person might do?
On what occasions do people sing and dance?
List the kinds of activities people do while listening to music?
List all of the musical instruments you know.
What styles of music are there?

For each interview, the researcher records the listed items in the
order in which the informant mentions them. For example, when asked
to list all of the musical instruments you know, a person might
begin: piano, guitar, violin, trumpet, etc.

Once the lists are acquired, an aggregate list is assembled in which
the items are ordered from the most commonly mentioned to the least
commonly mentioned. Usually, this aggregate omits those items that
were mentioned only once. In general, people tend to begin their
lists with the cognitively most salient items. So culturally
important items are more likely to appear near the beginning of the
list, and are most frequently mentioned. (For Western musicians,
instruments like the contrabassoon and didjeridoo are likely to
appear rarely and toward the end of the list.) A second version of
the aggregate freelist will be ordered according to the mean
rank-order. This can be calculated by numbering each item for each
informant, and then averaging the rank numbers. For example, if one
person lists the guitar first, and a second person lists the guitar
second, then the average rank for this instrument is 1.5.

A complication arises when there are items that might be regarded as
synonyms. For example, when asked to identify occasions when music
is played, responses might include "Easter," "Good Friday," "Easter
vigil," "Easter Sunday," "Orthodox Easter," and so on. The question
is whether these should all be coded as a single item, or as two or
more items. Similarly, one person might ennumerate soprano
saxophone, alto saxophone, tenor saxophone, etc., whereas another
person might simply identify "saxophone." In order to minimize
researcher bias, it may be useful to recruit one or more informants
to resolve such situations.

#### Recruitment

As with any sample, the best population estimates arise when there
is high data independence. Interviewing the members of a single
extended family, or a single social group of friends limits the
representativeness of the results. Anthropologists recommend
sampling individuals who are at least two social links apart. That
is, the relationship between sampled informants should be no closer
than "a friend of a friend." (Werner & Schoepfle, 1989, 1992). In
practical terms, the researcher can simply ask an informant ("Do you
know [list of already interviewed informants]?") before deciding
whether to invite someone to participate in a freelisting interview.

If the domain of knowledge is commonly shared across a culture,
representative results may be obtained with relatively few
participants. For example, if you are interested in the "holidays"
in some culture, you may find that three or four informants may be
sufficient. On the other hand, if the domain of knowledge is more
specialized (such as types of baked bread), then representative
results may require a greater number of participants, and
recruitment may require some eligibility criterion.

Results are more trustworthy when there is high inter-informant
agreement in the elicited terms. The proportion of shared terms
across participants should be reported along with the frequency and
rank-order lists. In general, an average inter-informant agreement
of 2/3 or more may be considered good or adequate. That is, if the
informants typically share two-thirds or more of the listed items,
then one can have greater confidence that the lists are
representative of a plausible cultural norm.

Freelisting is relatively quick and easy to do. In addition,
freelisting emphasizes culturally-grounded or "emic" conceptions and
tends to reduce the influence of researcher bias. However,
freelisting also has a number of disadvantages. De Munck (2009,
p.66) notes that freelists elicit terms that are at "the top of
people's heads" or on the "tip of their tongues." With more careful
reflection, consultants may change their views, and wish to offer
more nuanced distinctions. Once again, freelisting is typically an
exploratory method.

#### Pile Sorting

It is common for freelisting to be followed by *pile sorting.* Pile
sorting is a task in which respondents are asked to sort items into
categories. Two types of pile-sorting tasks are usually
distinguished: the *constrained* task in which the informant is told
the number of categories, and the *open-ended* task in which the
informant is free to determine the number of categories. Pile
sorting can be done with all kinds of items. For example, pile
sorting might be done with actual physical objects such as kitchen
utensils, fruits and vegetables, bird feathers, or spices.
Alternatively, printed cards may be used, such as photographs (e.g.,
different facial expressions), or written words. Photographs are
often easier for a respondent to sort than the actual physical
objects. In the case of sorting sounds, a computer display is
helpful, where icons representing different sounds can be moved
around the screen to form various groups.

It is worth noting that pile sorting is typically time consuming. It
is important to recruit participants who have time, and potentially
to provide a gift or offer compensation for their participation.
Pile sorting can prove to be particularly onerous if there are
rather few items, or an especially large number of items to be
sorted. If the items used for pile sorting come from an earlier
freelisting task, it may be useful to limit the number of items to
those mentioned two or more times, or three or more times, etc.

In pile sorting tasks, the temptation is to tell the informant to
sort items into "whatever categories you like." This can leads to
arbitrary criteria, such as sorting instruments according to their
weight or color. In instructing the informant, it can be useful to
explicitly reference culturally normative categories. For example,
one might instruct an informant to sort the items "in a way that
would make sense to a friend."

In order to minimize order effects, the items are usually randomized
for each participant. Participants are sometimes suspicious that
there is some special trick or ulterior motive in the task, so when
cards are used, it can be helpful to shuffle the cards in the
presence of the participant.

Once the sorting task has been completed it is useful to have the
participant describe each of the categories. Finally, encourage the
participant to provide a single word or short phrase as a
descriptive label for each category.

#### Hierarchies

The categories people use are often hierarchical organized. For
example, a Westerner might divide foods into things you drink and
things you eat. Things you eat might be subdivided into vegetable
and animal sources. Animal sources might be further subdivided into
meats and milk products, and so on. It is often useful to understand
the sorts of mental taxonomies that might exist for certain
phenomena.

In pile sorting tasks, one approach to better understanding mental
taxonomies is to follow the pile sorting by a subjective stepwise
clustering task. Suppose an informant has sorted the items into 12
categories. Having recorded the results, the researcher might then
instruct the informant as follows. "You have 12 piles here. Suppose
I told you that I want you to reduce the 12 to just 11. What two
piles are the most similar? What two piles would you put together?"
This reduction technique is then successively repeated until only
two piles remain. Although this procedure is more time-consuming, it
can better reveal latent hierarchies in the mental organization of
the categories. In addition, it can reconcile the usual divergence
between "lumpers" and "splitters" --- people who tend to favor small
numbers of groups and those who favor a larger number of groups.
Note that it may be useful at each stage to ask the informant to
re-label one or more categories.

An advantage of the stepwise clustering approach is that you may be
able to better reconcile different pile-sorts by different
informants. For example, one informant might produce 18 clusters,
another informant might produce 13 clusters, and a third informant
might produce 9 clusters. However, when asked to reduce the number
of clusters, the researcher might find that at 8 clusters, all three
informants are in very close agreement. The differences beyond 8
clusters might represent less culturally salient distinctions.

In the *constrained pile sort* task, the researcher tells the
informant the number of categories for sorting. This approach can be
used for hypothesis testing. For example, in previous work, the
researcher may have observed a tendency for informants to regard the
items as falling into the same five categories. As a test of this
observation, the researcher may explicitly ask several informants to
sort the items into five categories, without offering any additional
instruction. This can be used to test whether the five categories
are culturally robust.

Especially when working with people from an unfamiliar culture, it
may be difficult for the researcher to infer why a particular item
has been assigned to a particular category. In these cases, it can
be insightful simply to ask a participant to explain why they have
assigned a particular item to one group rather than another.

Pile sorting might be followed by more formal statistical methods.
For example, pile sorting might be followed by multi-dimensional
scaling (MDS) and/or formal hierarchical clustering (to be discussed
later). Both MDS and hierarchical clustering invite the researcher
to interpret the meaning of the resulting dimensions or the meaning
of each cluster. In order to minimize cultural bias, these
interpretations should not be done by the experimenter. It is more
appropriate to recruit one or more informant to offer possible
interpretations.

De Munck (1998) used freelisting, pile sorting, and multidimensional
scaling to examine the concept of romantic love among Lithuanians.
He found that Lithuanians tend to think of love along two dimensions
--- a *negative-positive* dimension and a *real-fantasy* dimension.
He then tested this interpretation with a follow-up experiment in
which Lithuanians were explicitly asked to rate a series of
love-related terms along the two dimensions. He found that
Lithuanians tend to view romantic love according to four prototypes:
fantasy-good love, fantasy-bad love, real-good love, and real-bad
love.

#### References:

Victor De Munck (1998). *Romantic Love and Sexual Behavior:
Perspectives from the Social Sciences.* Westport, CT: Praeger.

Victor De Munck (2009). *Research Design and Methods for Studying
Cultures.* Plymouth, UK: AltaMira Press




