


[GROUP TASK #17:]{.small} The Key of Funeral Marches

#### Task

Volume 17 of the New Grove Dictionary of Music and Musicians
identifies seven classic funeral marches. As it turns out 5 of those
7 marches are in the key of F minor. Test the hypothesis that
funeral marches tend to be composed in the key of F minor.

In order to calculate chi-square, we need to determine the
probability of any given musical work being written in F minor.

The following table shows a distribution of keys from a convenience
sample of 3,121 works from the common practice Western art music
tradition.

  ------------- ----------- -----------
  **Tonic**     **Major**   **Minor**
  C             358         6
  C#            2           2
  D             194         96
  D#            0           2
  Eb            125         0
  E             24          35
  F             757         10
  F#            2           4
  G             978         119
  G#            0           2
  Ab            11          0
  A             126         61
  Bb            198         2
  B             2           5
  **Totals:**   2,777       344
  ------------- ----------- -----------

Is the tendency to write funeral marches in F minor statistically
significant at the 0.01 level?

#### Rationale

This exercise provides additional practice in calculating
statistical significance using the chi-square test.
