---
title: "Goals"
author: "David Huron"
---

## Learning Objectives

Our goals are:

1.  To communicate the main concepts and techniques in modern
    empirical research.
    
2.  To provide practical experience in research skills, including
    posing research questions, formulating and operationalizing
    hypotheses, designing experiments and questionnaires, and
    analyzing data.
    
3.  To provide practical research advice.
    
4.  To expose participants to examples of empirical music studies
    through lectures and readings.
    
5.  To build critical skills when reading and interpreting empirical
    research studies --- identifying both strengths and weaknesses.
    
6.  To stimulate participants' creative imaginations in posing and
    pursuing musical questions.
    
7.  To provide sufficient background so that participants will feel
    confident in beginning their own program of empirical music
    research.
    
8.  To identify resources for continuing education in empirical
    musicology.
    
9.  To offer a philosophical framework for understanding how
    empirical methods can be contextualized within traditional
    concerns in the arts and humanities.
