



[GROUP TASK #1:]{.small} An Audience with God

#### Task

You have been granted an audience with God. Your group will be
allowed to ask Her three questions related to music. What questions
will you ask? Discuss the possibilities in your group and settle on
three questions. Write the questions down. Assign a different group
member to present each question to the larger workshop. Introduce
each question with a short preamble that sets the stage for your
question.

N.B. You are not allowed to ask "meta-questions" (such as "What is a
good question about music?").

#### Rationale

Ideally, research should focus on questions of the highest
importance. The conscientious researcher always trys to answer the
most important questions first.

Unfortunately, the most important questions cannot always be
answered given our limited resources and limited understanding.
Instead, we tend to focus on answering questions for which we have
the skills and resources to answer. By themselves, these questions
are often not very interesting or compelling.

The best research endeavors to connect good "top-down" questions
with good "bottom-up" research resources. Empirical research methods
can provide helpful resources for answering questions about music,
but these methods should not dictate our research agendas. In
learning how to use do empirical research, it is equally important
to learn to ask creative questions about music. The purpose of this
task is to get you thinking about the larger issues. As a
researcher, what do you *really* want to know?
