---
title: Grandparent Research - Revisited
author: David Huron
---

## Grandparent Research - Revisited


#### Even More Obvious

Notice that *hindsight bias* further aggrevates the *grandparent
effect.* It's not simply the case that research often demonstrates
the blindingly obvious. As we've seen, once people know the answer,
they are convinced that they knew it all along. So the price paid
for doing empirical research is three-fold:

the actual cost of doing the research (including time, effort,
resources)

the indignity of confirming that 95% of human intuitions are
correct, and

the ridicule from people---who having learned of your
results---will wrongly believe that they knew it all along.

If you choose to engage in empirical research, be prepared that
people will think you are naive and that you are involved in a
colossal waste of effort.

In the arts especially, we place a premium on imagination and
creativity. So among our arts colleagues, the majority of empirical
research is likely to be viewed as trite, dull, and unimaginative
--the very antithesis of what we expect in arts scholarship.




