

------------------------------------------------------------------------

### Grounded Theory

------------------------------------------------------------------------

In most empirical work, the emphasis is on testing a theory or
hypothesis. One begins with a theory and then collects data intended
to test the theory. A problem with this approach is that one must
start with a theory. What if you don't have a theory? Or worse yet,
what if all of our theories are wrong, misguided, or irrelevant? We
might spend our careers testing theory after theory --- showing that
none of them is any good.

An alternative approach might start with *observation* rather than
*theory.* Grounded Theory gets its name from the research being
"grounded" in observations. Start with the observations, and then
develop the theory from what you observe.

Grounded Theory was developed by sociologists Barney Glaser and
Anselm Strauss.

In traditional scientific method, we begin with a question, develop
a theory, and then test hypotheses that arise from that theory. In
grounded theory, it is less valuable to begin with a question. If
the researcher is guided by any question, it is: "What's going on?"
If the phenomenon being examined involves people, the motivating
question might be: "What is the main problem these people are facing
and how are they dealing with it?" Grounded Theory focuses on
observation.

Grounded Theory studies are not simply descriptive. Instead, they
are explanatory: the aim is to create a theory that explains the
observations. At the same time, efforts are made to avoid coming to
the observations with prior preconceptions. That is, the aim is to
develop theory "from the ground up." rather than interpreting the
observations in light of an already existing theory. Grounded Theory
aims to let a phenomenon speak for itself, and to reduce researcher
preconceptions from getting in the way.

### References

Kathy Charmaz (2000). Grounded theory: Objectivist and
constructivist methods. In Denzin, N.K. and Lincoln, Y.S. (eds.),
*Handbook of Qualitative Research,* 2nd edition. Thousand Oaks, CA:
Sage. pp. 509--535.

Kathy Charmaz (2006). *Constructing Grounded Theory.* London: Sage.

Barney Glaser & Anselm Strauss (1967). *Discovery of Grounded
Theory. Strategies for Qualitative Research.* Sociology Press.
