

**Hearing Screening Inventory**

#### Instructions

This questionnaire deals with a number of common situations. For each
question you should select the response that describes you and your
behaviors best. You can select from among the following response
alternatives;

  ----------------------------- ------------ ------------------ ---------------- -------------------------------
  **N**ever (or almost never)   **S**eldom   **O**ccasionally   **F**requently   **A**lways (or almost always)
  ----------------------------- ------------ ------------------ ---------------- -------------------------------


Simply circle the letter that corresponds to the first letter of your
choice. (If you normally use a hearing aid, answer as if you were not
wearing it.)

1.  Are you ever bothered by feelings that your hearing is poor? **N S
    O F A**
    
2.  Is your reading or studying easily interrupted by noises in nearby
    rooms? **N S O F A**
    
3.  Can you hear the telephone ring when you are in the same room in
    which it is located? **N S O F A**
    
4.  Can you hear the telephone ring when you are in the room next
    door? **N S O F A**
    
5.  Do you find it difficult to make out the words in recordings of
    popular songs? **N S O F A**
    
6.  When several people are talking in a room, do you have difficulty
    hearing an individual conversation? **N S O F A**
    
7.  Can you hear the water boiling in a pot when you are in the
    kitchen? **N S O F A**
    
8.  Can you follow the conversation when you are at a large dinner
    table? **N S O F A**
    
    Answer these questions using
      ---------- ------------- ---------------------------- ---------- ---------------
      **G**ood   **A**verage   **S**lightly below average   **P**oor   **V**ery poor
      ---------- ------------- ---------------------------- ---------- ---------------

    
9.  Overall, I would judge my hearing in my RIGHT ear to be **G A S P
    V**
    
10. Overall, I would judge my hearing in my LEFT ear to be **G A S P
    V**
    
11. Overall, I would judge my ability to make out speech or
    conversation to be **G A S P V**
    
12. Overall, I would judge my ability to judge the location of things
    by the sounds they are making alone to be **G A S P V**
