



**Instructions for Coding the Hearing Screening Inventory**

### Instructions

This screening inventory was developed by Stanley Coren and Ralph
Hakstian of the University of British Columbia. The inventory is
described in: Corren, S. & Hakstian, A.R. (1992). "The development
and cross-validation of a self-report inventory to assess pure-tone
threshold hearing sensitivity. *Journal of Speech & Hearing
Research*, Vol. 35, No. 4, pp. 921-928. This inventory is for
internal use only in the Cognitive and Systematic Musicology
Laboratory.

### Scoring instructions:

Responses are scored:

-   1 for "Never,"
-   2 for "Seldom,"
-   3 for "Occasionally,"
-   4 for "Frequently,"
-   5 for "Always"
    
-   1 for "good"
-   2 for "average"
-   3 for "slightly below average"
-   4 for "poor"
-   5 for "very poor"

The total score is simply the sum of the 12 responses.
(**Note: Items 2, 3, 4, 7, and 8 are reverse-scored.**)

### Score Interpretation:

-   scores from 12 to 27 are considered normal
-   28 to 36 indicates slight hearing impairment
-   37 to 60 indicates major hearing loss



