[GROUP TASK #3: Generating Theories (Part 2)]{.small}

#### Task

In the previous group task you were given a series of purported
findings from *The American Soldier* study and asked to suggest
theories that might account for the results. In fact, the "findings"
in the previous task *were precisely backward.* The actual findings
are given below. For each finding, suggest a theory that might
account for the result.

1.  Better educated soldiers suffered *fewer* problems in adjusting to
    military life than less educated soldiers.

    (i)
    

2.  Southern soldiers coped *worse* with the hot South Sea Island
    climate than northern soldiers.

    (i)
    

3.  *Black* privates were more eager to be promoted to noncommissioned
    officers than *white* privates.

    (i)
    

4.  Southern blacks preferred *northern white officers* over southern
    white officers..

    (i)
    

5.  As long as the fighting continued, soldiers were eager to return
    home. Once the war ended, soldiers felt *more* urgency to return
    home.

    (i)
    
