[GROUP TASK #3: Generating Theories]{.small}

#### Task

In the aftermath of World War II, the Pentagon carried out a
detailed study entitled *The American Soldier.* The study was based
on research involving 600,000 men and women in the service. Below
are five findings from this study. For each finding, suggest two
theories that might account for the result.

1.  Better educated soldiers suffered more problems in adjusting to
    military life than less educated soldiers.

    (i)
    
    (ii)

2.  Southern soldiers coped better with the hot South Sea Island
    climate than northern soldiers.

    (i)
    
    (ii)

3.  White privates were more eager to be promoted to noncommissioned
    officers than black privates.

    (i)
    
    (ii)

4.  Southern blacks preferred southern to northern white officers.

    (i)
    
    (ii)

5.  As long as the fighting continued, soldiers were eager to return
    home. Once the war ended, soldiers felt less urgency to return
    home.

    (i)
    
    (ii)
