

------------------------------------------------------------------------

## The Importance of Hypotheses

------------------------------------------------------------------------

#### Hypothesis:

A claim whose truth or falsity could, in theory, be tested (but not
proven) by making one or more observations.

#### Hypothesisless:

The state of being without a hypothesis.

In *exploratory* studies, the researcher makes no prior claim, and
therefore can never be wrong.

A common approach in traditional arts and humanities scholarship is
to make some observations, and then to present a story, theory or
analysis that makes sense of these observations. Since the story or
theory is not presented prior to making the observations, there is
no way to test the researcher's interpretation. When research is
done this way, the researcher always looks right since the
observations are always consistent with the theory.

Recall that *the best research invites failure.* We invite failure
by making predictions. That is, we invite failure by testing
hypotheses that are put forward before we collect or examine the
evidence.

There is an important role for descriptive and exploratory research.
Often we have no idea what needs to be explained. We may need to
"open the box" before we know what phenomena need to be theorized
about.

There is considerable attraction to pursuing solely descriptive or
exploratory research. Once again, if you don't test a hypothesis,
there is no chance of being wrong.

#### Hypothesislessness:

A persistent and sometimes chronic disease where a researcher is
perpetually without a hypothesis.

Some scholars just don't like being wrong. These scholars will tend
to focus exclusively on descriptive, analytic and exploratory
studies. The researcher who advances theories/analyses/stories only
*after* making observations is a researcher who will appear to be
omniscient.

The researcher who boldly proposes a theory or hypothesis before
collecting data is frequently regarded as cocky and
self-assured---the antithesis of the careful scholar. On the
contrary, this boldness is the requirement for intellectual
humility. The humble scholar is the one who is prepared to be
wrong---especially when he or she is shown to be wrong in public. It
is a mistake to believe that the researcher who proposes no theory
or hypothesis is the humblest of scholars.

**Slogan:** *Avoid chronic hypothesislessness.*




