

------------------------------------------------------------------------

## Questions, Theories, Conjectures, and Hypotheses

------------------------------------------------------------------------

#### Questions

A *question* is an expression of inquiry that invites or calls for a
reply. Research is typically motivated by a question.

*"Why do Beethoven's metronome markings seem so fast?"*

#### Conjectures

A *conjecture* is a supposition or speculative claim made about the
world. Conjectures are not directly testable.

*"The first musical instruments were probably drums."*

#### Hypotheses

A *hypothesis* is a testable conjecture. It is a claim or prediction
that can, in principle be compared to existing or future observations.

*"The music people experience as adolescents will remain the most
emotionally important music throughout their lives."*

#### Theories

A *theory* is an explanatory framework for understanding a phenomenon.
Theories typically propose some *cause* --- as in "*X* causes or
influences *Y.*" Theories often involve words like "because," "due
to," "affects," "influences," or "causes." Theories themselves are
rarely directly testable. Theories are used to generate conjectures
and hypotheses.

*"The reason why music from adolescence is so memorable is because
of the high levels of the hormone oxytocin experienced during
adolescence."*




