


[GROUP TASK #14:]{.small} Construct an Interview Guide

#### Task

Unlike the formal interview, an Open Interview does not employ an
exhaustive list of questions. Instead, open interviews are shaped by
an *interview guide*. The interview guide is a written document that
identifies the goals of the interviews, lists the topics of
interest, and provides some suggested questions.

Choose one of the following topics and then construct an appropriate
interview guide for conducting open interviews.

1. *How musicians practice.*
2. *DJs who work at weddings.*
3. *Film-music composer.*
4. *Music therapists working in hospital settings.*
5. *Composer for video games.*
6. *Conductors of community children's choirs.*

#### Sample

How might you recruit participants for your interview project?

#### Instructions

Spend no more than one or two minutes choosing a topic. Aim to
complete your interview guide in about five minutes. At the end,
have someone type-up the interview guide so your group truly
produces a document. Spend no more than one or two minutes
considering how you would recruit participants for the project.

#### Rationale

This task encourages thinking about how to maximize the insights
gained using a common exploratory research method.
