

------------------------------------------------------------------------

### Interviews in Translation

------------------------------------------------------------------------

In carrying out interview research, we are often trying to cast a
wide net so as to include voices that are not always heard. In
seeking a diversity of viewpoints, your research is likely to take
you to individuals or communities where you don't speak the language
(and they don't speak your's). Ideally, you would make the long-term
investment to learn the language, but that's not always practical.
Consequently, you may need to rely on a translator to help conduct
the interview.

In the world of languages *translators* are people who take a
written text and render a parallel text in another language. The
word *interpreter* is used to identify people who render the spoken
word into another language. In the case of live interviews, you will
make use of an "interpreter" rather than a "translator."

Very few people are trained as professional interpreters. (It is
something of a grueling occupation that involves especially rigorous
training.) In field research, it is much more likely that you will
simply find a bilingual individual who speaks both a language you
know and the language of the people you want to interview.
Unfortunately, these "convenience interpreters" raise all sorts of
methodological issues.

Suppose your goal is to interview Maria, a Quechua-speaking Peruvian
indian. You don't speak Quechua, but fortunately, you have
befriended Jorge, who is a native Quechua speaker who also has
fair-to-good English skills. When you spend time in the field, you
will inevitably form your closest friendships with those people you
most easily communicate with. If Jorge is the only Quechua speaker
in the village who speaks English, you are sure to rely a great deal
on him.

In such situations, much of your understanding of the local culture
will be filtered through Jorge's eyes. On the one hand, Jorge is
likely to have some very useful insights into his own culture. On
the other hand, Jorge is likely to filter what other people say in
accordance with what he thinks they mean, or what he thinks they
should be saying, or more importantly (even if unconsciously), what
he thinks you're looking for or want to hear. Remember, if Jorge
speaks the best English, this means he is also likely to be the
person in the village who is most outward looking, and probably the
most favorably disposed to Western culture. By definition, this
makes him not representative of the people in his village.

Before the interview, take time to explain to Jorge what you are
doing. Tell him you very much value his views. But when interviewing
other people, you expect that they will have different viewpoints
that you truly want to hear. Even if Jorge thinks the interviewee is
wrongheaded, you want to know --- insofar as possible --- what the
interviewee has said. Tell Jorge that he will be of greatest value
to your research if he simply does his best to translate Maria's
Quechua into English without adding or subtracting anything. Also
tell him that, after the interview is over, you'd like to hear his
particular take on what Maria said. For example, if Jorge has
background knowledge that will help make sense of what she said,
you'd like to hear that. Similarly, if Jorge thinks she was
exaggerating or lying, or not telling you the whole story, you'll
certainly welcome his input.

When actually conducting an interpreted interview *eye contact* and
*body language* are of paramount importance. As an interviewer, your
most important rule is to keep your eyes and attention focused on
the interviewee (Maria) --- not on the interpreter (Jorge). You want
to ensure that Maria is the center of attention. Through your body
language, you want to indicate that this is a conversation between
you and Maria. With untrained interpreters, it is very easy for the
conversation to degrade into long interactions between you and the
interpreter, or between the interviewee and the interpreter. If you
can, teach your interpreter how to use his or her eyes to ensure
that the conversation is between you and the interviewee. A good
interpreter should not simply look at whoever is talking. Instead, a
good interpreter will cast their eyes back-and-forth between the
interviewer and interviewee. This will subtley tell Maria that she
is talking to you, not to Jorge.

Where possible, always record the conversation. Even if you have no
other way of translating the conversation, listening to the
recording after the interview is over can alert you to potential
problems. Be vigilant for interactions that don't seem right. For
example, pay attention to disparities between the durations of
answers and translations. Suppose you ask the question "Are you
married?" Maria's response might be 20 seconds in duration, yet
Jorge's translation might be a brief three seconds: "Yes, she's
married to Simón." Conversely, if Maria gives a short response, and
Jorge's translation is somewhat long, this should also be cause for
suspicion. If you are suspicious, isolate a particular sound bite,
play it to Jorge, and ask him what precisely did Maria say here.
This exercise will also help Jorge learn how to become a better
interpreter. Of course, practice helps a lot. The more experience
you have with your interpreter, they better he/she will become.

Given the problems with untrained interpreters, you should endeavor
to try to access the information through several different methods.
One approach is simply to schedule a repeat interview. If there is
more than one person with whom you share a common language, you
might seek input from another source, or employ a second
interpreter. Remain vigilant for other sources of information that
might converge or confirm findings in your interviews.




