

------------------------------------------------------------------------

### Welcome and Personal Introductions

------------------------------------------------------------------------

#### Organization

1.  Welcome to Ohio State University. For those of you who are from
    out-of-town, welcome to Columbus. And for those of you who have
    traveled further afield, welcome to Ohio and to the United States.
    We will do introductions in a minute, but first let's deal with
    some organizational issues.
2.  My names is David Huron [and my name is Dan Shanahan]. We're
    the instructors of this workshop.
3.  Introduce ____________ (workshop assistant). If you
    haven't already completed payment, __________ will be
    happy to help you.
4.  Regarding wireless: EDUROAM - from other institutions; otherwise
    PUBLIC free wifi. (Many local eateries and coffee shops have free
    WIFI.)
5.  No need to take detailed notes. Everything covered will be
    distributed as printed notes. However, it is helpful to take notes
    on the main ideas since research suggests that moderate
    note-taking assists in learning and retention.
6.  A handful of presentations (about 2 hours in total) I have
    pre-recorded on video (to save my voice). The videos are also
    available to you.
7.  In addition, all of the powerpoint presentations---will also be
    made available. (We'll pass around a data stick at the end of
    each day, so you can copy them onto your computers.)
8.  Many group activities planned.
9.  15 minute breaks at 10:00 and around 2:30. (End of day may vary.)
10. During breaks, remember that we're located in a library. It's okay
    to converse here in the seminar room and downstairs in the cafe,
    but please be considerate and avoid conversing immediately outside
    the seminar room in the main library area.
11. Lunch is 70 minutes --- from noon to 1:10.
12. Coffee shop on ground floor.
13. We will have daily feedback questionnaires---which will help us
    with mid-workshop corrections. Will be anonymous, coded by our
    workshop assistant.
14. There will be (modest) homework each night.
15. Friday afternoon we hope to have time for each of you to discuss
    your own research plans---and to receive feedback. [Your homework
    on Thursday night will be to prepare your mini presentation; don't
    prepare before Thursday however.]
16. Learning by slogan.

#### Personal Introductions

1.  Personal introductions by participants.
2.  (Introduce self 2nd-to-last): I am a music lover;
3.  a 13-year-old meets Mrs. Lanuette
4.  my experience reading feminist literature (Betty Friedan, Germaine
    Greer, Susan Brownmiller and Gloria Steinem)---men dominate
    conversations; my first empirical study: measuring the amount of
    speaking time
5.  began my career as a composer: led me to psych of music &
    ethnomusicology
6.  no formal training in psych, methodology or stats
7.  my background in music; intellectual history; philosophy; lapsed
    Adorno; PhD musicology in Britain
8.  Please call me David.

Dan Shanahan's introduction.

#### Background

1.  Outside of the arts, the principal purpose of scholarship is the
    acquisition of new knowledge (or the application of that knowledge
    for practical purposes, e.g. technology, medicine).
2.  In the arts, scholarship is more than that. Art has no pre-defined
    purpose. Art can entertain us, amuse us, enlighten us, even insult
    us. The notion that art has no pre-defined purpose means that art
    can be used for all sorts of purposes---including no purpose at
    all.
3.  Not all arts scholarship is oriented toward the acquisition of new
    knowledge. For example, the purpose of much scholarly writing
    might be to enhance our enjoyment of music.
    E.g. When I travel, I find it useful to read about a place before
    I visit. It often makes the experience more meaningful and
    interesting. Similarly, when viewing a painting or listening to a
    piece of music, some knowledge of the history of that object often
    enhances my experience of it.
4.  Much music scholarship---including music history---serves this
    function. In the case of my own field (music theory), a lot of
    analysis, is what Davy Temperley would call "suggestive." The
    analysis is not necessarily intended to tell you truthfully how
    the music is put together, but to suggest a way of listening that
    might enhance the listening experience.
5.  My piano teacher's story about Bach's *Art of Fugue*: the apex of
    contrapuntal art, Bach's awareness of his impending death, and
    signing his life's work. My disappointment in learning that this
    story wasn't true.
6.  In some ways, the origins of modern musicology arose from
    disappointment when music lovers discovered that stories about
    their favorite musicians were fabricated or exaggerated. The
    "truth" can serve to increase our experience of beauty.
7.  Susan McClary's description of Beethoven's fifth?? as a musical
    portrayal of rape.

#### Learning Objectives

1.  Distribute handout: review learning objectives.
