

------------------------------------------------------------------------

### The Null Hypothesis

------------------------------------------------------------------------

Recall that a hypothesis is is a testable conjecture. It is a claim or
prediction that can, in principle be compared to existing or future
observations. An example of a hypothesis might be:

Most listeners prefer familiar music over unfamiliar music.

It is common in empirical research to refer to the research hypothesis
using the upper-case letter **H**. Since empirical studies often test
more than one hypothesis, it is common to number the hypotheses. Even
if there is only a single hypothesis, authors commonly still refer to
it as **H1**.

H1. The use of rhyming words in musical lyrics increases the
likelihood that listeners will understand the sung word.

Recall that *refutation* is easier than *confirmation*. It is easier
to show that the statement "All swans are white" is wrong (by
observing a single non-white swan) than to show that the statement is
right (by observing all possible swans). This asymmetry is captured in
our slogan: *Aim not to be right, but to be not not right.*

There are an infinite number of incorrect hypotheses, and most of
these hypotheses are not interesting. Usually, a researcher is hoping
that their hypothesis is correct. However, it is impossible to show
that a hypothesis is true. It is easier to show that a hypothesis is
incorrect. As a result, empirical researchers restate their hypothesis
in a *reverse* formulation. Here is an example:

H~[0]{.small}~. The use of rhyming words in musical lyrics *does
not* increase the likelihood that listeners will understand the sung
word.

This "reverse formulation" of a hypothesis is referred to as the *null
hypothesis.* The null hypothesis is abbreviated using the upper-case
letter **H** followed by the subscript zero: **H~[0]{.small}~**. For
convenience, it is often simplified to **H0** without the subscript.

In empirical research, we rarely directly test the research
hypothesis. Instead, we test the null hypothesis. Rather than testing
the research hypothesis (and vainly hoping that it is "confirmed"), we
test the null hypothesis (and hope that it is rejected). (Once again,
we aim to be not not right, rather than aiming to be right.)

In analyzing our observations, we will use statistical methods to
measure, not the probability that our research hypothesis is
consistent with our data, but the probability that the null hypothesis
is consistent with our data. If the probability is low, then we will
conclude that the null hypothesis is inconsistent with our data. We
will conclude that our data provides no reason to accept the null
hypothesis. Having dismissed the null hypothesis, our research
hypothesis will have survived the test. ("The best research invites
failure.")

In many books on statistics, the rejection of null hypothesis is
considered grounds for "accepting the research hypothesis." This is a
old traditional formulation that should be avoided. A better
formulation is the one given in the previous paragraph: having
concluded that the data are *not* consistent with the null hypothesis,
we will infer that the data are consistent with the research
hypothesis. Said another way, we can claim that the research
hypothesis has survived an empirical test.

Once again, in empirical research, we do not engage in "confirmation."
We never show things are "true." Our data don't "support" or "prove"
or "demonstrate" anything. At best, we can claim that the data *are
consistent with the hypothesis.*

So let's review. Because refutation is easier than confirmation, we
test hypotheses by attempting to refute them. The researcher
reformulates the research hypothesis as the null hypothesis.
Statistical methods are then used to calculate the probability that
the data are consistent with the null hypothesis. If the probability
is low, we conclude that the data are not consistent with the null
hypothesis, and instead infer that the data are consistent with the
reverse of the null hypothesis---namely, the research hypothesis.
Traditionally, statisticians refer to this procedure as *disproving
the null hypothesis*. However, good researchers avoid this language.
Instead, we conclude simply that the data are not consistent with the
null hypothesis---and conversely, that the data are consistent with
the research hypothesis.




