

------------------------------------------------------------------------

## Ollen Musical Sophistication Index

------------------------------------------------------------------------

*Available online at:* `http://marcs-survey.uws.edu.au/OMSI/`

How old are you today?

_____ age in years

At what age did you begin sustained musical activity? "Sustained
musical activity" might include regular music lessons or daily musical
practice that lasted for at least three consecutive years. *If you
have never been musically active for a sustained time period, answer
with zero.*

_____ age at start of sustained musical activity

How many years of private music lessons have you received? *If you
have received lessons on more than one instrument, including voice,
give the number of years for the one instrument/voice you've studied
longest. If you have never received private lessons, answer with
zero.*

_____ years of private lessons

For how many years have you engaged in regular, daily practice of a
musical instrument or singing? "Daily" can be defined as 5 to 7 days
per week. A "year" can be defined as 10 to 12 months. *If you have
never practiced regularly, or have practiced regularly for fewer than
10 months, answer with zero.*

_____ years of regular practice

Which category comes nearest to the amount of time you currently spend
practicing an instrument (or voice)? Count individual practice time
only; not group rehearsals.

[ ] I rarely or never practice singing or playing an instrument
[ ] About 1 hour per month
[ ] About 1 hour per week
[ ] About 15 minutes per day
[ ] About 1 hour per day
[ ] More than 2 hours per day

Have you ever enrolled in any music courses offered at college (or
university)?

[ ] No (Skip to #8)
[ ] Yes

(If Yes) How much college-level coursework in music have you
[completed]{.ul}? *If more than one category applies, select your
[most recently]{.ul} completed level.*

[ ] None
[ ] 1 or 2 NON-major courses (e.g., music appreciation, playing or
singing in an ensemble)
[ ] 3 or more courses for NON-majors
[ ] An introductory or preparatory music program for Bachelor's
level work
[ ] 1 year of full-time coursework in a Bachelor of Music degree
program (or equivalent)
[ ] 2 years of full-time coursework in a Bachelor of Music degree
program (or equivalent)
[ ] 3 or more years of full-time coursework in a Bachelor of Music
degree program (or equivalent)
[ ] Completion of a Bachelor of Music degree program (or
equivalent)
[ ] One or more graduate-level music courses or degrees

Which option best describes your experience at composing music?

[ ] Have never composed any music
[ ] Have composed bits and pieces, but have never completed a
piece of music
[ ] Have composed one or more complete pieces, but none have been
performed
[ ] Have composed pieces as assignments or projects for one or
more music classes; one or more of my pieces have been performed
and/or recorded within the context of my educational environment
[ ] Have composed pieces that have been performed for a local
audience
[ ] Have composed pieces that have been performed for a regional
or national audience (e.g., nationally known performer or ensemble,
major concert venue, broadly distributed recording)

To the best of your memory, how many live concerts (of any style, with
free or paid admission) have you attended as an audience member in the
[past 12 months]{.ul}? Please do not include regular religious
services in your count, but you may include special musical
productions or events.

[ ] None
[ ] 1 - 4
[ ] 5 - 8
[ ] 9 - 12
[ ] 13 or more

Which title best describes you?

[ ] Nonmusician
[ ] Music-loving nonmusician
[ ] Amateur musician
[ ] Serious amateur musician
[ ] Semiprofessional musician
[ ] Professional musician




