---
title: Operationalize This
author: David Huron
---

#### Operationalizing Hypotheses

A hypothesis cannot be tested unless each of its terms or concepts
can be translated into a measurable variable or a concrete
procedure.

E.g. *Listening to Mozart makes people smarter.*

  --------------- ----------------------------------------------------------------------
  ***Concept***   ***Possible operationalization***
  "smarter"       will score higher on the Stanford-Binet IQ test
  "Mozart"        all sound recordings that claim the music is composed by W.A. Mozart
  "listening"     conscious while being exposed to 20 minutes of sound recordings
  "people"        2nd-year undergraduate music students from the Ohio State University
  --------------- ----------------------------------------------------------------------

Notice that operationalizing a hypothesis never captures the full
breadth of the original claim. In the above case, the hypothesis has
been transformed to something much more narrow:

When awake 2nd-year OSU music students are exposed to 20 minutes
of sound recordings of music deemed to be composed by W.A. Mozart
they will score higher on the Stanford-Binet IQ test when compared
with students who had not been exposed to such music.

Whether some statement is viewed as a hypothesis or a conjecture
depends on whether its terms can be operationalized.

#### Operationalize the following hypotheses:

1.  Women like to dance more than men.
    
2.  The progression from dominant to subdominant is more common in
    Reggae music than other musics.
