

------------------------------------------------------------------------

## A Quantiative Study of Chromaticism - Perttu (2007)

------------------------------------------------------------------------

Read Perttu (2007). A quantitative study of chromaticism: Changes
observed in historical eras and individual composers. *Empirical
Musicology Review,* Vol. 2, No. 2, pp. 47-54.

Answer the following questions:

1.  What kinds of studies are these? Exploratory, descriptive,
    correlational, experimental, pilot, modeling?
    
    
    
2.  Perttu never formally states any hypotheses, but they are implied.
    What is the hypothesis for the first study? The second study? The
    third study?
    
    
    
3.  For Study #1, what is the *hypothesis?*
    
    
    
4.  For Study #1, what is the *hypothesis?*
    
    
    
5.  For Study #1, what is the *population?*
    
    
    
6.  For Study #1, what is the *sample?*
    
    
    
7.  What sampling method(s) does Perttu use for the first two studies?
    Convenience, simple random, systematic, stratified, quota? What
    sampling method(s) does Perttu use for the (third) Mozart study?
    
    
    
8.  What exclusionary criterion were used in the sampling?
    
    
    
9.  In what ways does the sample differ from the population?
    
    
    
10. Why sample only one note from each work?
    
    
    
11. What are the theoretical terms in the hypothesis?
    
    
    
12. How are the theoretical terms operationalized?
    
    
    
13. What two pieces of information were collected for each sampled
    theme?
    
    
    
14. What bias is associated with the right-hand margin when sampling
    from notated scores?
    
    
    
15. Is Study #1 an *experimental* or *correlational* study?
    
    
    
16. Is the conclusion for Study #1 properly phrased?
    
    
    
17. Is this grandmother research?
    
    
    
18. If someone were to repeat this study, what changes would you
    recommend?
    
    
    




