

# Music Research Program Survey

For a number of years, music students at OSU have been participating
in a variety of experiments sponsored by the School of Music. The
purpose of this survey is for us to gain a better perspective on those
students who participate in our experiments. Since OSU music students
differ in several ways from other musicians as well as the general
population, this information helps us better understand the
limitations when generalizing research conclusions to other groups of
people.

This questionaire is entirely anonymous. Please do not write your name
or any other identifying marks on this paper. Note that data collected
from this survey may be made available to other researchers, but that
all data will be preserved or distributed in a completely anonymous
format.

### DEMOGRAPHIC INFORMATION

1.  What is your age? __________ years.
    
2.  Please circle MALE or FEMALE.
    
3.  Is English your first language? (answer YES or NO):
    ________
    
4.  Are you fluent in any language other than English? If so, indicate
    the other language(s): ________________
    
5.  Were you born in the United States? (answer YES or NO):
    ________
    
6.  Were you raised predominantly in the United States? (answer YES or
    NO): ________
    
7.  Were your born in Ohio? (answer YES or NO): ________
    
8.  Were you raised predominantly in the state of Ohio? (answer YES or
    NO): ________
    
9.  On a scale from 1 to 10, where 1 means highly **rural** and 10
    means highly **urban**, circle the value which best characterizes
    your up-bringing.
      ---------------- -- --- -- --- -- --- -- --- -- --- -- --- -- --- -- --- -- --- -- ---- -- ----------------
      (highly rural)      1      2      3      4      5      6      7      8      9      10      (highly urban)
      ---------------- -- --- -- --- -- --- -- --- -- --- -- --- -- --- -- --- -- --- -- ---- -- ----------------

    
    
10. How would you characterize your ethnic background?
    ___________________________________________________
    
11. Have you ever **lived** in a country other than the United States?
    (Y/N): __________
    
    If, so please identify the country(s) in which you have lived and
    for how long. Use the space provided below.
    
    
    
    
12. Have you ever travelled outside of the United States? (Y/N):
    ____________
    
    If so, please identify all of the countries in which you have
    travelled. Use the space provided below.
    
    
    
    
    
    
    
13. On a scale from 1 to 10, where 1 means "working-class" and 10
    means "upper-class", circle the value which best characterizes
    your socio-economic background.
    
      ----------------- -- --- -- --- -- --- -- --- -- --- -- --- -- --- -- --- -- --- -- ---- -- ---------------
      (working-class)      1      2      3      4      5      6      7      8      9      10      (upper-class)
      ----------------- -- --- -- --- -- --- -- --- -- --- -- --- -- --- -- --- -- --- -- ---- -- ---------------
14. Do you have a part-time job? (Y/N): ________
    
    If so, approximately how many hours per week do you work?
    __________ hours/week
    
15. In your childhood home environment, how many people were normally
    living together? Include yourself, parents, siblings,
    relatives/others in your tally: ________
    
16. In your childhood home environment, how many people were involved
    in regular music-making activities? Include yourself, parents,
    siblings, relatives/others in your tally: ________
    
17. In your childhood home environment, how many people took formal
    music lessons? Include yourself, parents, siblings,
    relatives/others in your tally: ________

### MUSIC BACKGROUND AND STUDIES

1.  What is your major?
    __________________________________________________
    
2.  Have you ever taken private singing lessons? (answer YES or NO):
    ________
    
    If YES, at what age did you begin lessons? ________ years
    of age
    
    If YES, how many years of lessons have you taken? ________
    years in total
    
    How would you characterize your voice? (soprano, alto, baritone
    ...) __________
    
3.  Are you an instrumentalist who cannot/does not sing? (answer YES
    or NO): ________
    
4.  Are your currently a participant in a choir? (answer YES or NO):
    ________
    
5.  Do you frequently sing in the shower or when bathing? (answer YES
    or NO): ________
    
6.  Do you frequently sing along with recorded music? (answer YES or
    NO): ________
    
7.  This question pertains to instrumental music only. In this
    question, we'd like you to identify any/all instruments that you
    play. For all instruments you may play, please tell us the age
    when you began playing the instrument, the age at which you began
    lessons on the instrument (if applicable), and the total number of
    years of instruction (if applicable). Begin with your most
    proficient instrument.
    
      ---------------------------------- ---------------------------------- ---------------------------------- --------------------------------
      Instrument                         Age you began playing              Age you began lessons              Total years of lessons
      ________________   ________________   ________________   _______________
      ________________   ________________   ________________   _______________
      ________________   ________________   ________________   _______________
      ________________   ________________   ________________   _______________
      ---------------------------------- ---------------------------------- ---------------------------------- --------------------------------

    
    
8.  At what age did you decide you wanted to pursue a music degree at
    university?
    
    __________ years old.
    
9.  If you were **not** enrolled in a music program, what other area
    of study would you pursue?
    
    __________________________________________________
    
10. Excluding ensemble rehearsals, roughly how many hours per week to
    you practice? (include all instruments/voice): ________
    hours
    
11. Roughly how many hours per week do you rehearse with ensembles?
    ________ hours
    
12. Roughly how many hours per week do you engage in music
    rehearsals/practising that are unrelated to your OSU music
    program? ________ hours
    
13. In the past two years, and excluding OSU music assignments, have
    you ever transcribed (notated from sound) a musical work? (answer
    YES or NO): ________
    
14. Do you have perfect pitch? (answer YES or NO):
    ______________
    
    If you have perfect pitch, is it restricted to a particular
    instrument?
    
    (answer YES or NO): ________; If YES, identify the
    instrument(s): ____________________
    

### LISTENING HABITS & TASTES

The following questions are intended to inform us about your listening
habits and musical preferences.

1.  Help us to identify the source of most of your listening. For each
    of the following sources, please indicate the number of hours per
    week of listening. Exclude practising and rehearsals.

      ------------------ ---------------------------------
      **source**         **hours each week**
      Radio              __________ hours/week
      MTV/videos         __________ hours/week
      CD/tape/stereo     __________ hours/week
      Live music         __________ hours/week
      Internet audio     __________ hours/week
      Library/reserves   __________ hours/week
      Other              __________ hours/week
      ------------------ ---------------------------------

2.  Excluding practising, **where** do you do most of your listening?
    Please indicate the percentage of your listening the occurs in
    each of the following locations:

      ------------------ -----------------------------------------------------------------
      **location**       **percentage of listening**
      at home            ________ %
      automobile         ________ %
      at a friend's      ________ %
      at church/temple   ________ %
      school             ________ %
      pub/club/bar       ________ %
      gym                ________ %
      other              ________ % please specify location __________
      ------------------ -----------------------------------------------------------------

3.  Where do you do most of your practising?

      -------------- -- -- -----------------------------------------------------------------
      **location**         **percentage of practising**
      at home              ________ %
      at school            ________ %
      other                ________ % please specify location __________
      -------------- -- -- -----------------------------------------------------------------

4.  What percentage of your total listening coincides with other
    (non-listening) activities? (Exclude practising and rehearsing.)
    Circle one.
    
    (listen **without** other tasks)

5.  How many CDs/tapes/records do you think you **own**?
    __________ recordings
    

6.  On average, how many music recordings do you acquire per year?
    __________ recordings
    

7.  Do you download music from the web? (answer YES or NO):
    ________
    

8.  Excluding rehearsals and practising, do you listen to MORE or LESS
    music now than you did before attending university? (answer MORE
    or LESS): ________
    

9.  At what age do you think you listened to the most amount of music?
    ____________ years old
    

10. How similar would you say your musical tastes are to the musical
    tastes of the **GENERAL POPULATION**? Answer on a scale of 1 to 10
    where 1 indicates "completely different" and 10 indicates "almost
    identical":
      ------------- -- --- -- --- -- --- -- --- -- --- -- --- -- --- -- --- -- --- -- ---- -- -----------
      (different)      1      2      3      4      5      6      7      8      9      10      (similar)
      ------------- -- --- -- --- -- --- -- --- -- --- -- --- -- --- -- --- -- --- -- ---- -- -----------

    
    

11. How similar would you say your musical tastes are to the musical
    tastes of your **biological MOTHER**? Answer on a scale of 1 to 10
    where 1 indicates "completely different" and 10 indicates "almost
    identical":
    
    check box if question not applicable [ ]
    
      ------------- -- --- -- --- -- --- -- --- -- --- -- --- -- --- -- --- -- --- -- ---- -- -----------
      (different)      1      2      3      4      5      6      7      8      9      10      (similar)
      ------------- -- --- -- --- -- --- -- --- -- --- -- --- -- --- -- --- -- --- -- ---- -- -----------

    
    

12. How similar would you say your musical tastes are to the musical
    tastes of your **biological FATHER**? Answer on a scale of 1 to 10
    where 1 indicates "completely different" and 10 indicates "almost
    identical":
    
    check box if question not applicable [ ]
    
      ------------- -- --- -- --- -- --- -- --- -- --- -- --- -- --- -- --- -- --- -- ---- -- -----------
      (different)      1      2      3      4      5      6      7      8      9      10      (similar)
      ------------- -- --- -- --- -- --- -- --- -- --- -- --- -- --- -- --- -- --- -- ---- -- -----------

    
    

13. How similar are your musical tastes to the musical tastes of your
    **closest MALE friend**? Answer on a scale of 1 to 10 where 1
    indicates "completely different" and 10 indicates "almost
    identical":
      ------------- -- --- -- --- -- --- -- --- -- --- -- --- -- --- -- --- -- --- -- ---- -- -----------
      (different)      1      2      3      4      5      6      7      8      9      10      (similar)
      ------------- -- --- -- --- -- --- -- --- -- --- -- --- -- --- -- --- -- --- -- ---- -- -----------

    
    

14. How similar are your musical tastes to the musical tastes of your
    **closest FEMALE friend**? Answer on a scale of 1 to 10 where 1
    indicates "completely different" and 10 indicates "almost
    identical":
      ------------- -- --- -- --- -- --- -- --- -- --- -- --- -- --- -- --- -- --- -- ---- -- -----------
      (different)      1      2      3      4      5      6      7      8      9      10      (similar)
      ------------- -- --- -- --- -- --- -- --- -- --- -- --- -- --- -- --- -- --- -- ---- -- -----------

    
    

15. Please tell us about your favorite music.
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    

16. Please tell us about any music you consider really bad.
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
