

------------------------------------------------------------------------

## Replication and Pre-Reviewing

------------------------------------------------------------------------

The following general announcement was distributed May 9, 2014 by the
*Journal of Experimental Psychology: General.* This is one of the
flagship journals of the *American Psychological Association.* This
call for papers embodies two efforts intended to counteract *positive
results bias*: namely pre-reviewing and replication:

``

#### Call for Replication Studies Papers

The Journal of Experimental Psychology: General is inviting
replication studies submissions. The Journal values replications and
may publish them when the work clearly contributes to its mission.
This includes contributions with interdisciplinary appeal that address
theoretical debate and/or integration, beyond addressing the
reliability of effects.

The Journal preference is for replication plans to be submitted to the
Journal before data collection begins. A proposal should provide a
strong motivation for the study in the context of the relevant
literature, details of the design, sample size, and planned analyses.
The editorial team may encourage a replication project, based on
external guidance. Final manuscripts will be evaluated through further
external review. Submit through the Manuscript Submission Portal
(http://www.apa.org/pubs/journals/xge) and please note that the
submission is a proposal for replication. Replication articles will be
published online only and will be listed in the Table of Contents in
the print journal.

Questions can be addressed to the Editor, Isabel Gauthier
(gauthier.jepg@gmail.com) or to the Editorial Associate, Jennifer
Richler, (richler.jepg@gmail.com).

Editorial Office
Journal of Experimental Psychology: General




