

------------------------------------------------------------------------

## The Rhetoric of Science

------------------------------------------------------------------------

#### The Rhetoric of Science

Scholarship is a form of rhetoric. The principal products of
research are written documents and spoken presentations.

Most of the books sold in bookstores are classified as *fiction*.
Fiction writers tell us that they make up their stories; the stories
they write are products of their imaginations. Other materials are
sold under the category *non-fiction* and this includes scholarship
of all sorts, including science. On what basis can anyone make a
distinction between *fiction* and *non-fiction*?

If you pick up a copy of a professional journal, such as the
*Journal of Experimental Biology*, what evidence do you have that
the articles it contains are not also works of fiction? How do we
know that the authors haven't simply made it all up? On what basis
would one ever be justified in thinking that an article in *JEB* is
more believable or credible than (say) a chapter in the *Anthology
of Science Fiction and Fantasy*?

All researchers are story-tellers of a certain sort. All knowledge
claims (*scientia*) are narratives. Science is a form of
story-telling, a form of rhetoric. But that doesn't mean that
science doesn't have special properties as a narrative form.

Suppose you wanted to tell a *really good* story. What makes a story
truly captivating? Not all stories are equally compelling, and if we
aim to be good story tellers, it is helpful to understand what makes
some stories really grab the human mind. It is helpful to know
something about different forms of rhetoric.

#### Prophecy

In 1494, Christopher Columbus embarked on his second voyage to the
Americas. On May 5th of that year he landed on the island now known
as Jamaica. He told the local native Jamaicans that in two days
time, the moon would rise up and swallow the sun --- plunging the
midday into darkness. (In short, he predicted a solar eclipse.) When
the eclipse did in fact take place, the native Jamaicans were
dumbstruck: they were deeply impressed by Columbus' apparent
prophetic abilities.

There are only three way to account for the accuracy of any
prediction. Either:

1.  The person has some sort of direct communication channel to God.
2.  The person's prediction was just darn lucky. Or
3.  The person is in possession of a useful theory of the natural or
    social world that makes it possible to produce such predictions
    with a high likelihood of success.

Throughout history, the most powerful form of rhetoric has been
*prophecy.* People have been most impressed, when someone made a
prediction that was then borne-out. In most of the world's
religions, prophetic texts are among the most revered documents.

Of course, some predictions are more impressive than others. Suppose
I predicted that tomorrow it will rain in Seattle. I doubt anyone
would be impressed if it did, in fact, rain (even if the official
weather forecast didn't call for precipitation). The reason why this
prediction would be less impressive is that there is a high
probability of simply guessing correctly. That is, it is much more
likely that my accurate prediction was "just darn lucky" in the case
of predicting rain in Seattle compared with Christopher Columbus
correctly predicting a solar eclipse.

So why might people respect or even revere science more than (say)
novels or poetry? The answer lies in the mind's disposition to be
impressed by prophecy. Science provides compelling stories because
it relies on the rhetorical power of prophecy. Its persuasive power
lies in improbable predictions. Christopher Columbus could have told
the Jamaicans a story about how, *in the past*, he had seen "the
moon swallow the sun." They might have thought this story was
interesting and entertaining. But instead, Columbus told them a
story about the *future* --- a story that (improbably) came to pass.
A future-tense story is much more impressive than a past-tense
story. Yes: science is a form of narrative story-telling, but it
commands special interest and respect, because it draws on the most
powerful of all known rhetorical devices.

Our second slogan reminds us that science is a form of rhetoric, and
that it's rhetorical strength comes from making predictions:

**Slogan:** *The rhetoric of science is the rhetoric of prophecy.*

#### Prediction vs. Explanation

A common view is that science is an *explanatory* discipline;
science aims to help us *understand* phenomena. This is only
partially correct; it misses the main point. There are many other
human activities that provide explanations for phenomena. History
explains past events. Aesthetics explains art. Religion explains the
meaning of life. Poetry explains the human heart. In each of these
cases, people may draw great satisfaction from the explanations
offered. Who is to say which explanations are True in any ultimate
sense?

The key difference between science and most other intellectual
activities is not *explanation* but *prediction.* Scientific
explanations are used to make predictions; when the predictions
derived from these accounts are borne-out, people tend to ascribe
greater credence to the originating explanation. It is *prediction*
that is key. *Science is a community of scholars who hold each other
to a methodological commitment to making and testing predictions.*

We will never know for certain whether any scientific explanation is
True. What makes scientific narratives compelling to human minds is
not their truth value, but their prophetic value. When people say
that science is just another form of story-telling, the implication
is that it is no different than other forms of story-telling.
However, some forms of story-telling are more compelling than
others. Science is perhaps the most engaging form of story-telling
human minds have yet discovered.




