---
title: Qualitative AND Quantitative
author: David Huron
---

## Qualitative AND Quantitative


#### Introduction

At this point it should be clear that both qualitative and
quantitative research methods hold advantages and disadvantages.

Qualitative (and exploratory methods generally) are essential to
good research. Especially when your investigations take you into new
or unfamiliar territory (such as spending time in an unfamiliar
culture) qualitative methods have much to offer. In new
circumstances we need to be vigilant for things we haven't
considered. We need to be open, allowing the new environment or
phenomenon to shape our thinking. Although our perceptions are
inevitably limited by our existing preconceptions, we still need to
make an effort to give primacy to "grounded" observations. The good
scholar is the acute observer. A singular focus on quantitative *a
priori* hypothesis testing might be wrong-headed in many situations.

Participant-observation, structured and unstructured interviews,
grounded theory, phenomenological introspection, and other
qualitative methods can lead us to important insights. These
insights may even reshape the research questions. Although we may
have started with a particular pre-existing agenda, we need to be
prepared that the situation might render that agenda irrelevant or a
low priority. A volunteer might enter a particular community with
the aim of (say) enhancing prenatal health care. But the situation
might cause a realignment of priorities: one might discover that
domestic violence is a more pressing problem, and might be the
principal impediment to improving prenatal care.

At the same time, qualitative research methods have their
limitations. When theories are formed after the evidence is
assembled, there is the danger of double-use data. When asked what
evidence do you have in support of a theory, it's not legimate to
point to the same observations you used to form the theory in the
first place.

More problematic is that an exclusive reliance on qualitative or
exploratory methods means that theories are never tested. When we
rely exclusively on qualitative methods, we are never inviting
failure. When we are never shown to be wrong, the inevitable
consequence is that we become over-confident in ourselves. By
contrast, the whole quantitative enterprise is oriented to
minimizing Type I errors---the errors where we thing our wrong
theories are right.

Finally, qualitative research tends to rely excessively on case
studies or anecdotal evidence. As we have seen, there is a
rhetorical and educational value to anecdotes, cases, or examples.
However, whenever people give examples, we tend to gravitate to our
BEST examples, not our most representative or TYPICAL examples.
Examples, cases, or anecdotes hold a rhetorical power that exceeds
their informativeness.

As we noted earlier, quantitative methods are important for two
reasons. First, measuring things can help us discover phenomena that
might otherwise be invisible. Second, measuring or counting can make
it clear when we are wrong. Counting and measuring are useful tools,
like a magnifying glass or a stethoscope.

#### Research Identity

Much of the rhetorical friction between qualitative and quantitative
methods arise from issues of identity. Methods should be regarded as
tools, not badges of identity. A person should not think of
him/herself as either a qualitative or quantitative researcher. Nor
should people identify themselves as a "empirical" researcher.
Resist the temptation to link your identity to a method. Instead,
think of yourself as a scholar who is conscientious about choosing
the most appropriate method for whatever project you are pursuing.
The person who identifies with a particular method is probably
someone who is only familiar with one method. As the saying goes:
"For the person with a hammer, all the world looks forever like a
nail."

#### References:

David Huron (1999). *The 1999 Ernest Bloch Lectures. Lecture 3.
Methodology: The New Empiricism: Systematic Musicology in a
Postmodern Age.*




