


[TASK #6:]{.small} From Question to Theory

#### Introduction

There are two ways to formulate theories. One approach is to examine
some evidence or research results and then try to explain the
evidence by creating a plausible story (using the word *because*).
This is what we did in our earlier exercise regarding findings from
*The American Soldier* study. This approach is known as *post hoc
theorizing.*

A second approach to theory formation begins with a question. We ask
a question (which may arise from intuition or past informal
experience), and then invent a plausible answer. This approach is
known as *a priori theorizing.*

#### Task

Formulate a musically-pertinent question. It may be one of the big
"God" questions you discussed earlier. Better yet, consider choosing
a much more modest question that you think is interesting. Consider
two or three theories pertinent to the question. The theories don't
need to explain every aspect of the question, (or even the main part
of the question). It is better if your theories address one aspect
or component of the question (i.e., Don't try to explain the whole
world at once.).

Having considered different possibilities, decide on a single theory
that you think would warrant empirical exploration. (You don't
necessarily have to think it is a *good* or even *adequate* theory.)

Write a two- or three-sentence description of your theory. Be sure
to use the word *because* in your theory.

If we have time within the workshop, share your question and theory
with your participant group. If you can, would you describe your
theory as *post hoc* or *a priori*?

#### Rationale

The purpose of this exercise is to develop skills in theory
formation.
