

------------------------------------------------------------------------

## Citations, Mentions, and Quotations

------------------------------------------------------------------------

#### Citations

A proper citation occurs when the cited publication supports the
immediately preceding claim. An example would be:

*In the 19th century, most minor-mode music is actually faster in
tempo than most major-mode music (Post & Huron, 2009).*

The abbreviation *cf.* refers to the Latin "confer" --- which is
best translated as "compare." Since the abbreviation represents a
single word, we write *cf.* rather than *c.f.* In scholarly
citations, *cf.* is used to mean *compare* or *contrast.* It is used
when the cited publication:

1.  makes the same point, but using a somewhat different approach
    (not discussed here)
2.  makes the same point, but only in passing; for example, the
    cited publication presents data that supports this point but the
    author(s) of the cited work don't draw attention to this result
    (not discussed here)
3.  makes the same point but provides a refinement (not discussed
    here), or
4.  takes an opposing or alternative point of view (which will not
    be discussed here).

An example would be:

*Most music in the minor mode is slower in tempo than music in the
major mode (cf. Post & Huron, 2009).*

When a cited work is contrary to a claim, it is common to add the
phrase "although see:"

*The amount of syncopation in American popular music increased
steadily from 1850, peaking around 1970 (Smith, 1998; Smith &
Jones, 1999; Jones & White, 2008; although see Black & White,
2006).*

In complicated situations, an explanatory footnote or endnote is
appropriate. Footnotes are ubiquitous in historical journals,
however publishers generally dislike footnotes and usually ask
authors to minimize or restrict their number.

#### Topical Citations

A *topical citation* refers to a publication that is cited because
it deals with the same or related topic. The cited work may be old,
deal with somewhat different concerns, or be superceded by later
research. The topical reference doesn't support a particular claim
made in the text. Nevertheless, topical references help to situate
the current work in a network of past and ongoing research and
demonstrates the author's awareness and engagement with the work of
other scholars.

*Considerable research has been carried out regarding human facial
expressions (Duchenne, 1862; Darwin, 1872, Spitz & Wolf, 1946;
Ekman, 1973, 1980, 2006; Fridlund, 1994; Freitas-Magalhães, 2007)*

Although much research is published today in English, there is
important research (especially earlier research) published in many
different languages. It is bad scholarship --- and also deeply
annoying (and offensive) for researchers in non-English countries
--- when important historical work is not cited simply because it is
not in English. In addition to research in major European languages
(like German, French and Italian), there is excellent research in
other languages that is not widely known. For example, important
scholarship in philosophy is found in Danish, important work in
mathematics is published in Hungarian, essential work in history is
published in Chinese, and superb work in chemisty is written in
Russian. In the case of music psychology, one can find important
work published in Swedish. It is appropriate to provide topical
citations to works that are in languages you don't understand.
Topical references aren't merely a "courtesy."

In music analysis, it is common for different theorists to offer
rather different analyses of the same musical work. Too often, one
observes a regretable tendency for music scholars *not* to cite
other analyses of the same work --- simply because the author
disagrees with another author's analysis. This is simply bad
scholarly practice. *Always cite those who disagree with you, and
with whom you disagree.* Disagreements need to be kept professional
rather than personal: failing to cite the work of people will simply
make them angry and transform a civil disagreement into a personal
dispute.

#### Deceptive Citation

The deceptive citation is one that appears to support a claim, but
doesn't. An author might write to the effect that:

*X is bigger than Y (Smith, 2004).*

Smith (2004) might discuss the relative size of X and Y, but if
Smith (2004) doesn't present any evidence supporting the claim that
X is bigger than Y, then the citation is deceptive. An especially
egregious version of the deceptive citation is what might be called
the "opinion-data swap." It may be that Smith (2004) expresses the
opinion or speculates that X is bigger than Y, but presents no
evidence in support of this view. In this case, the above citation
is wholly deceptive: it presents opinion as though it were
supporting evidence.

#### Second-Hand Citations

A second-hand citation is characterized by phrases like "as quoted
in," "as cited in," or "as discussed in." In general, one should
simply look up the original work and read it for yourself --- and so
avoid a second-hand citation. However, on occasion, a second-hand
citation is unavoidable. For example, an author (say Rossi, 2012)
might cite or quote from Li (1965). You may be unable to find a copy
of Li (1965) for yourself, or you may be unable to read the language
in which Li (1965) is written. In these cases you may use a
second-hand citation:

*According to Li "All observed billbirds are nosiceptors." (Li,
1965, as quoted in Rossi, 2012).*

*It has been claimed that all observed billbirds are nosiceptors
(Li, 1965, as cited in Rossi, 2012).*

It is surprisingly common in published articles for references to
contain a typo or mistake. Page numbers may be wrong, or the volume
may be given as 23 instead of 32. Never simply copy a reference from
another publication without checking the accuracy. Scholars can look
very foolish when such errors are propagated through several
publications. Arnold (1991) makes a typographical mistake in citing
Novak (1985), and then Brown (1996), Cohen (2000), Donald (2005),
Ellis (2012) all perpetuate the same typo. Evidently, none of the
authors has checked the original publication!

There is one circumstance when you should always draw attention to a
second-hand citation --- even if you have looked up the original.
Some scholars are especially conscientious and methodical in
identifying pertinent research that other scholars have overlooked.
If the reference is to a publication that has been generally
neglected, you should also draw attention to the scholar who
tracked-down the overlooked work. For example, Kim (2010) may have
cited the work of Ferdinand (1937) --- work that has otherwise not
been recognized by other authors. In this case, it is appropriate to
acknowledge the role of Kim in re-discovering this neglected
research:

*Ferdinand carried out early work on this issue (Ferdinand, 1937;
as noted by Kim, 2010).*

#### Mentions

A "mention" is a referenced publication that is included out of
courtesy. Sometimes authors include such references to flatter a
particular person --- such as a person who is likely to be recruited
as a reviewer for the manuscript. Spurious mentions to one's own
previous publications would be considered a "mention" and should be
avoided.

#### Quotations

Use quotations sparingly. There are two circumstances when quotation
is warranted:

1.  **The Elegant quote.** When the author has expressed an idea in
    an especially elegant or memorable way. The 18th century English
    poet, Alexander Pope, provides a nice characterization of this
    type of quotation: To quote Pope: *"What oft was thought, but
    ne'er so well exprest."*
2.  **The Factual quote.** When you want to demonstrate or establish
    a fact, such as that the author really did say something
    extreme, contentious, or questionable, or that the author was
    misquoted by another scholar.

The most common mistake is to resort to quotation because you don't
understand what the author is saying. Complicated quotations usually
suggest that the author quoting the passage hasn't been able to make
sense of what was written. We might call this the **Mystifying
quote.** In effect, the mystifying quote says: "I don't really
understand what this person is saying, so I'll just simply pass
along the quote and hope that you, dear reader, can make some sense
of this ..."

#### General Remarks

Few experiences are more discouraging for a scholar than to read a
publication that fails to cite one's own research when the research
is clearly pertinent. Scholarship is a community enterprise, and so
you need to participate as a good citizen. Acknowledge the hard work
of others, in the same way that you hope others will acknowledge
your own hard work. Make the extra effort to identify all of the
pertinent research literature and to cite this work in your writing.
In particular, don't neglect historical literature and literature
published in languages you don't understand.

As a general principle, aim to cite more research in your writing
than is typical in your discipline. The corrolary of this principle
is that you should read more publications than is common among your
colleagues, and read beyond the core journals in a field.

Finally, read (or at least skim) all of the literature you cite. Of
course, this is essential when the purpose of the citation is to
support a claim you are making.

#### Reference:

Post, O., & Huron, D. (2009). Music in minor modes is slower (except
in the Romantic Period). *Empirical Musicology Review,* Vol. 4, No.
1, pp. 1-9.




