

------------------------------------------------------------------------

### Reading #3: Turner & Huron (2008)

------------------------------------------------------------------------

Read: Ben Turner and David Huron (2008). A comparison of dynamics in
major- and minor-key works. *Empirical Musicology Review,* Vol. 3, No.
2, pp.64-68. The article can be found at:
<https://kb.osu.edu/dspace/bitstream/handle/1811/31941/EMR000047a_Turner_Huron.pdf?sequence=1

While reading this article, keep the following comments and questions
in the back of your mind:

1.  In this first reading, you are not expected to understand any of
    the statistics, so don't worry about the statistical descriptions.
2.  What is the hypothesis?
3.  Do the authors have more than one hypothesis?
4.  What are the main terms in the hypothesis that need to be
    operationalized?
5.  How do they determine "major" and "minor"? Are you convinced by
    the method they used?
6.  How do they measures the dynamic level?
7.  They sampled only the first dynamic level encountered in each
    piece. Could you propose a better method?
8.  They identified 192 pieces for possible sampling, but they only
    analysed 48? Why didn't the authors examine all 192 pieces?
9.  What is the conclusion?
10. In the conclusion, do the authors use suitably circumspect
    language?
