

------------------------------------------------------------------------

### Reading #4: Huron (2001)

------------------------------------------------------------------------

Read: David Huron (2001). What is a musical feature? Forte's Analysis
of Brahms's Opus 51, No. 1, Revisited. *Music Theory Online,* Vol. 7,
No. 4. The article can be found at:
<http://www.mtosmt.org/issues/mto.01.7.4/mto.01.7.4.huron.html

N.B. You can hear a recording of the 1st movement of Brahm's string
quartet no. 1 on Youtube at:
<http://www.youtube.com/watch?v=AlnhPbsnDFc&feature=related

The article is divided into two parts. The first part asks "What is a
musical feature?" The second part presents some analytic observations
of a string quartet movement by Brahms. While reading this article,
keep the following comments and questions in the back of your mind:

1.  What motivated this study?
2.  What is "distinctiveness?"
3.  What music is used as the "control" group for the analysis? Is
    this music an appropriate control?
4.  What rationale is given for the choice of feature measurements?
5.  What is the main conclusion of the analysis section of the
    article?
6.  What is the main conclusion for the entire paper?
7.  If you were Allen Forte, how would you respond to this article?
