

------------------------------------------------------------------------

### Research Research

------------------------------------------------------------------------

There is no recipe for doing research; there is no standard plan or
omnibus template. Instead, there are some commonly used techniques,
such as cluster analysis, pile-sorting, and chi-squared tests. But
these techniques don't tell you how to do research. Research
involves a lot of different activities, and new approaches are
constantly appearing.

What we call "research methodology" is primarily a bunch of pointers
--- a bunch of *do's* and *dont's.* Actually, most of the important
research advice is in the form of *dont's*: avoid multiple tests,
avoid essentializing terms, don't try to explain the whole world at
once, avoid chronic hypothesislessness, avoid sticky data, beware of
post-hoc theorizing, etc.

When we do research, with luck, we learn some new things about our
field of interest. But doing research also teaches us about research
itself.

In pursuing your research, be prepared to make mistakes. Even if you
avoid all of the pitfalls discussed in this course, there will be
new, not-yet-identified pitfalls waiting to be discovered. It may be
that your most important contribution to scholarship will be
identifying yet another methodological pothole to be avoided.

Our slogan reminds us that learning about research is itself an
ongoing enterprise:

**Slogan:** Don't be afraid to add your own slogans.




