

------------------------------------------------------------------------

### Some Advice About Reviewing

------------------------------------------------------------------------

In general, reviewing is an important part of the scholarly
enterprise. Unfortunately, it tends to be invisible. Consider a
journal that publishes (say) 20 articles per year. It is common to
commission three reviews for each article. Many journals have a
rejection rate of about 80%, which means that 4 out of 5 submissions
are rejected. So the 20 published articles were likely selected from
100 submissions, which means perhaps 300 reviews were written.
That's a lot of work, and it is almost entirely unseen.

If you've been submitting manuscripts for publication, it follows
that you should do your part by contributing to the review process
as well. That's what peer review means.

Each journal has its own editorial policy and different journals may
have different procedures for reviewing submissions. In some cases,
the journal may send "Instructions for Reviewers." More commonly,
the editor will simply provide a sentence or two describing what is
expected.

#### The Review

A review is typically divided into four parts: (1) recommendation,
(2) summary, (3) major concerns, and (4) detailed comments. Reviews
are typically between 2 and 5 pages in length.

#### Recommendation

The first part is a one or two sentence recommendation. There are
four common outcomes: (1) accept outright, (2) accept pending minor
revisions, (3) revise and resubmit, and (4) reject.

Here are some examples of recommendations:

"This is an admirable paper and I'm delighted to recommend
publication."

"I enjoyed reading this paper, although I have reservations about
the presentation of the data --- especially Figure 2. If the
author(s) is/are able to address this concern (see below), I am
happy to recommend publication."

"While the subject matter of this paper is interesting, I regret
that there are a number of methodological issues that need to be
addressed (see below). Accordingly I would recommend that the
author(s) revise and resubmit."

"I recognize that the author(s) carried out a considerable amount
of work in pursuing their study. However, I regret that there are
several serious methodological problems that make it impossible
for the author(s) to draw any reasonable conclusions. I recommend
that the paper be rejected."

Be aware that your recommendation is just that --- a recommendation.
It is the Action Editor (the person in charge of the review process
for this particular manuscript) who will normally make the final
assessment. Very rarely, the Editor will intervene and override the
activities of the Action Editor, but this is extremely rare.

When the review process is complete, the Action Editor will send you
copies of all of the reviewers' reviews, as well as the action
letter, conveying the Action Editor's recommendation. So you'll get
to see what other reviewers wrote about the same submission.

#### Summary

After the assessment comes the summary. In about a paragraph, you
should describe the paper in your own words. The purpose is to show
that you understood the manuscript. This is not always
straightforward. Unlike published articles, submitted manuscripts
vary considerably in their quality. Sometimes the manuscript is
disorganized and it is hard to decipher what the researcher(s) did.
It is possible that the research is actually quite well done, but
the writing quality is so bad that it is hard to realize this as a
reviewer. (Remember that many researchers do not have English as a
first language.)

As a reviewer, you might end up criticizing something that's not
germane. For example, the author(s) might have done the right thing,
but they just didn't describe it adequately. You can waste a lot of
time because you misunderstand something.

By summarizing the work, you make it clearer to the author(s) that
they have communicated (or failed to communicate) their work. Don't
be afraid to say you had trouble understanding the paper. For
example, in your summary, you might want to say something like "If I
understand the paper correctly, the author(s) ..."

#### Major Concerns

This is the place to identify any major concerns you have. It is
common to number each issue successively. It is useful to present
the concerns in their order of importance. This ordering will help
the author(s) understand the relative gravity of each point. The
Action Editor will also appreciate your ordering. For example if all
three reviewers identify a particular problem near the top of their
list, this lends weight to the overall assessment.

In your recommendation, you may draw attention to particularly
onerous problems.

#### Detailed Comments

This is the place to identify simpler issues. Detailed comments
might refer to simple problems such as spelling erorrs, confusing
sentence structure, recommendations that the author(s) cite other
existing research, etc. Typically, detailed comments begin with the
page/line numbers, followed by the comment. Don't be afraid to make
specific recommendations. E.g.

pg.7/lines 10-11 "Our results establish that ..." Please
replace by "Our results are consistent with the view that ..."

#### General Advice

It is common for new reviewers to feel unqualified. You may feel
that you really don't know very much about the specific area of
research addressed in the manuscript. Unfortunately, there are
simply not enough experts in the world. All scholars must leave
their comfort zone, otherwise nothing would get done.

The most common mistake for new reviewers is to be overly critical.
Avoid harsh language. People pour their hearts into their research.
It is discouraging to receive rejection notices and disappointing to
receive perpetual "revise and resubmit" letters. But if the
assessments are written using acerbic language, this just deepens
the wounds --- for no good reason.

Be helpful. Instead of saying "Why did you do this?" Offer specific
advice. Tell the author what to say. Don't be afraid to suggest
replacement wording. Tell them what to do to bring the work up to
sufficient quality.

Reviews are teachable moments. Take the opportunity to help your
colleagues become better researchers. Explain the problems. Share
your knowledge. Describe what they've done wrong. The vast majority
of music scholars have never heard of "multiple tests." If
necessary, provide a reference to a book (include page numbers) that
describes some methodological difficulty. Even if you recommend
rejection, the entire exercise can still contribute to the
discipline as a whole by helping other researchers to become better
at their craft. Especially when I was younger, I learned a lot from
the comments reviewers made about my work.

Be circumspect about asking for additional work. There is no such
thing as a definitive study, so there is no end to the number of
follow-up studies that can be done. Especially when contrasted with
books, journal articles are meant to be "contributions" ---
research that adds another piece to the puzzle. An excellent
experiment may very well invite an obvious follow-up experiment to
test one of the main assumptions. Don't be quick to ask for the
follow-up. Here's why.

I've had the following experience many times in my career: With
student X we carried out a study. Student X then graduates, leaves
the field, or gets a job in a small music department with little
opportunity for research. We submit the study and the Action Editor
asks for a follow-up study or experiment. I am busy with other
projects and find that I'm unable to interest another student in
continuing the work. Moreover, if a second student joins the
project, they are apt to be the third author on the resulting paper
and that often seems to them like insufficient recognition for their
work. (The new student doesn't realize how much work the first
student did.) As a result the project gets abandoned. Some years
later a colleague (one of the original reviewers) approaches me at a
conference and says "I read this really interesting study you did
some time ago; whatever happened to that?" :-)

In the end, ask yourself the following question: "Will publishing
this article as it is (without any additional work) contribute to
our knowledge?" If the answer is yes, don't hold things up by asking
for another experiment.

Defend good work. If you think the work is good, say so. Many
journals have a policy that if any one reviewer recommends
rejection, then the Action Editor is expected to reject the
submission. If you write enough reviews, you will have the
experience where a perfectly good piece of research is rejected
because one of the other reviewers was feeling spiteful or ornery.
An Action Editor will have second thoughts if the other reviewers
are enthusiastic about the work.

#### Signed Reviews

Most journals practice blind peer review in the sense that the
reviewers remain anonymous. Most (though not all) journals also
remove identifying information about authorship. You can often guess
the identity of an author by the subject matter and by the cited
references. However, as you gain experience, one tends to mistrust
these guesses. Try to avoid the mental guessing-game about
authorship. It's just not helpful and is ultimately another form of
research bias.

In some cases, reviewers will identify themselves in their reviews
(so-called "signed reviews"). This is usuallly done when the
reviewer thinks it would be beneficial for the author(s) to contact
the reviewer for further clarification. For example, a reviewer
might be quite enthusiastic about the research but has specific
suggestions that could be better conveyed by conversation. It is
rare for "rejections" to be signed.

#### Annual Report

Reviewing is something you can report in your annual report to your
department chair. Being asked to review for journals testifies to
your status in the scholarly community. When reporting, it's
important to maintain the anonymity of the author(s). Instead,
simply report that you did a review for Journal X.

Once you have reviewed for several journals, this is something you
may wish to include on your C.V. under SERVICE or PROFESSIONAL
SERVICE. E.g. "Manuscript reviewing done for *Music Perception,
Music Theory Spectrum,* and *Music Theory Online."*




