

------------------------------------------------------------------------

### Sampling - A Practical Problem

------------------------------------------------------------------------




#### What Do People Listen To?

One of the most difficult sampling problems in music is the
seemingly simple task of determining what everyone in some
population listens to. How would you assemble a representative
sample of the music listened to by people living in Ohio?

#### Music Sampling in Micronesia

In my study of music and globalization in Micronesia, my first aim
was to determine how much Western music people listened in different
Micronesian cultures. I visited several different cultures: Majuran,
Palauan, Yapese, Ulithian, Kosraean, Pohnpeian Chamoru and Rotan.
How do you suppose I estimated what people are listening to?

For this project, I used two different sampling methods, and then
compared the results from both methods. Fortunately, I found that
the results for the different sampling methods were very similar.
That is, the different approaches produced converging evidence.

The first method involved radio sampling. Arriving on an island, I
used a standard radio and scanned both the AM and FM frequency
ranges. I made a note of every radio station that was accessible on
the island. Micronesia is a remote place: one island had as many as
three radio stations; most had just one accessible radio station; a
couple had no access to AM or FM radio broadcasts at all. Once I had
identified the accessible stations, I randomly sampled the music
available on these stations at random times over a week or so. For
each musical selection, I identified and coded the origin of the
music. Some music is clearly local (sung in the local language).
Other music is regional (from other cultures in Micronesia). Yet
other music has a Pacific origin (such as music from Fiji, Tahiti,
or Hawaii). Finally, other music originates in other
places---notably American and British pop. From this information, I
could characterize the proportion of music available via radio whose
origin is local, regional, Pacific, or Western.

The second method involved asking locals where I might be able to
purchase music on the island. For each island, I would track down
the "three best places" where one can purchase CDs and tapes. On a
few islands, there are specialty shops were you can buy music. On
most islands, the only place to purchase music is at a general store
of some description. In a few cases, the sum total of music for sale
might be just a dozen cassette tapes sitting on a shelf or in a
glass display. For each of the three "best" places to purchase
music, I made a complete inventory of all the music available for
purchase. From this information, once again I calculated the
proportion of music whose origin is local, regional, Pacific, or
Western.

Some islands (like Majuro), music on the radio is dominated by
American pop music. Interestingly, the music for sale on that island
was also dominated by American pop. At the other extreme, on an
island like Palau, music on the radio is dominated by local Palau
music, and that is paralleled by the high proportion of Palau music
available for sale in the shops. In short, I found a high positive
correlation between the musical origin of broadcast music and the
musical origin for retail music.

What music are people listening to in Micronesia? It is impractical
to follow local people during their day and chronicle what they are
listening to. We don't really know. However, if we operationalize
*what people listen to* in two different ways (radio and sales),
there is converging evidence that is consistent with the theory that
radio programing and local music sales provide reasonable estimates
of local listening habits.




